/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;
import io.metaloom.loom.db.jooq.tables.interfaces.IModelVersion;

import java.util.UUID;


import static io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModelVersion implements VertxPojo, IModelVersion {

    private static final long serialVersionUID = 1L;

    private UUID   uuid;
    private UUID   modelUuid;
    private String json;
    private UUID   nextVersionUuid;
    private UUID   prevVersionUuid;

    public ModelVersion() {}

    public ModelVersion(IModelVersion value) {
        this.uuid = value.getUuid();
        this.modelUuid = value.getModelUuid();
        this.json = value.getJson();
        this.nextVersionUuid = value.getNextVersionUuid();
        this.prevVersionUuid = value.getPrevVersionUuid();
    }

    public ModelVersion(
        UUID   uuid,
        UUID   modelUuid,
        String json,
        UUID   nextVersionUuid,
        UUID   prevVersionUuid
    ) {
        this.uuid = uuid;
        this.modelUuid = modelUuid;
        this.json = json;
        this.nextVersionUuid = nextVersionUuid;
        this.prevVersionUuid = prevVersionUuid;
    }

        public ModelVersion(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }

    /**
     * Getter for <code>public.model_version.uuid</code>.
     */
    @Override
    public UUID getUuid() {
        return this.uuid;
    }

    /**
     * Setter for <code>public.model_version.uuid</code>.
     */
    @Override
    public ModelVersion setUuid(UUID uuid) {
        this.uuid = uuid;
        return this;
    }

    /**
     * Getter for <code>public.model_version.model_uuid</code>.
     */
    @Override
    public UUID getModelUuid() {
        return this.modelUuid;
    }

    /**
     * Setter for <code>public.model_version.model_uuid</code>.
     */
    @Override
    public ModelVersion setModelUuid(UUID modelUuid) {
        this.modelUuid = modelUuid;
        return this;
    }

    /**
     * Getter for <code>public.model_version.json</code>.
     */
    @Override
    public String getJson() {
        return this.json;
    }

    /**
     * Setter for <code>public.model_version.json</code>.
     */
    @Override
    public ModelVersion setJson(String json) {
        this.json = json;
        return this;
    }

    /**
     * Getter for <code>public.model_version.next_version_uuid</code>.
     */
    @Override
    public UUID getNextVersionUuid() {
        return this.nextVersionUuid;
    }

    /**
     * Setter for <code>public.model_version.next_version_uuid</code>.
     */
    @Override
    public ModelVersion setNextVersionUuid(UUID nextVersionUuid) {
        this.nextVersionUuid = nextVersionUuid;
        return this;
    }

    /**
     * Getter for <code>public.model_version.prev_version_uuid</code>.
     */
    @Override
    public UUID getPrevVersionUuid() {
        return this.prevVersionUuid;
    }

    /**
     * Setter for <code>public.model_version.prev_version_uuid</code>.
     */
    @Override
    public ModelVersion setPrevVersionUuid(UUID prevVersionUuid) {
        this.prevVersionUuid = prevVersionUuid;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ModelVersion (");

        sb.append(uuid);
        sb.append(", ").append(modelUuid);
        sb.append(", ").append(json);
        sb.append(", ").append(nextVersionUuid);
        sb.append(", ").append(prevVersionUuid);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IModelVersion from) {
        setUuid(from.getUuid());
        setModelUuid(from.getModelUuid());
        setJson(from.getJson());
        setNextVersionUuid(from.getNextVersionUuid());
        setPrevVersionUuid(from.getPrevVersionUuid());
    }

    @Override
    public <E extends IModelVersion> E into(E into) {
        into.from(this);
        return into;
    }
}
