/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;
import io.metaloom.loom.db.jooq.tables.interfaces.INamespace;

import java.time.LocalDateTime;
import java.util.UUID;


import static io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Namespace implements VertxPojo, INamespace {

    private static final long serialVersionUID = 1L;

    private UUID          uuid;
    private String        name;
    private UUID          rootContentUuid;
    private String        meta;
    private String        pathPrefix;
    private String        modelFilters;
    private LocalDateTime created;
    private UUID          creatorUuid;
    private LocalDateTime edited;
    private UUID          editorUuid;

    public Namespace() {}

    public Namespace(INamespace value) {
        this.uuid = value.getUuid();
        this.name = value.getName();
        this.rootContentUuid = value.getRootContentUuid();
        this.meta = value.getMeta();
        this.pathPrefix = value.getPathPrefix();
        this.modelFilters = value.getModelFilters();
        this.created = value.getCreated();
        this.creatorUuid = value.getCreatorUuid();
        this.edited = value.getEdited();
        this.editorUuid = value.getEditorUuid();
    }

    public Namespace(
        UUID          uuid,
        String        name,
        UUID          rootContentUuid,
        String        meta,
        String        pathPrefix,
        String        modelFilters,
        LocalDateTime created,
        UUID          creatorUuid,
        LocalDateTime edited,
        UUID          editorUuid
    ) {
        this.uuid = uuid;
        this.name = name;
        this.rootContentUuid = rootContentUuid;
        this.meta = meta;
        this.pathPrefix = pathPrefix;
        this.modelFilters = modelFilters;
        this.created = created;
        this.creatorUuid = creatorUuid;
        this.edited = edited;
        this.editorUuid = editorUuid;
    }

        public Namespace(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }

    /**
     * Getter for <code>public.namespace.uuid</code>.
     */
    @Override
    public UUID getUuid() {
        return this.uuid;
    }

    /**
     * Setter for <code>public.namespace.uuid</code>.
     */
    @Override
    public Namespace setUuid(UUID uuid) {
        this.uuid = uuid;
        return this;
    }

    /**
     * Getter for <code>public.namespace.name</code>.
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.namespace.name</code>.
     */
    @Override
    public Namespace setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>public.namespace.root_content_uuid</code>.
     */
    @Override
    public UUID getRootContentUuid() {
        return this.rootContentUuid;
    }

    /**
     * Setter for <code>public.namespace.root_content_uuid</code>.
     */
    @Override
    public Namespace setRootContentUuid(UUID rootContentUuid) {
        this.rootContentUuid = rootContentUuid;
        return this;
    }

    /**
     * Getter for <code>public.namespace.meta</code>. Custom meta properties to the element
     */
    @Override
    public String getMeta() {
        return this.meta;
    }

    /**
     * Setter for <code>public.namespace.meta</code>. Custom meta properties to the element
     */
    @Override
    public Namespace setMeta(String meta) {
        this.meta = meta;
        return this;
    }

    /**
     * Getter for <code>public.namespace.path_prefix</code>. Prefix for webroot paths
     */
    @Override
    public String getPathPrefix() {
        return this.pathPrefix;
    }

    /**
     * Setter for <code>public.namespace.path_prefix</code>. Prefix for webroot paths
     */
    @Override
    public Namespace setPathPrefix(String pathPrefix) {
        this.pathPrefix = pathPrefix;
        return this;
    }

    /**
     * Getter for <code>public.namespace.model_filters</code>. filter for models that can be used in the namespace
     */
    @Override
    public String getModelFilters() {
        return this.modelFilters;
    }

    /**
     * Setter for <code>public.namespace.model_filters</code>. filter for models that can be used in the namespace
     */
    @Override
    public Namespace setModelFilters(String modelFilters) {
        this.modelFilters = modelFilters;
        return this;
    }

    /**
     * Getter for <code>public.namespace.created</code>.
     */
    @Override
    public LocalDateTime getCreated() {
        return this.created;
    }

    /**
     * Setter for <code>public.namespace.created</code>.
     */
    @Override
    public Namespace setCreated(LocalDateTime created) {
        this.created = created;
        return this;
    }

    /**
     * Getter for <code>public.namespace.creator_uuid</code>.
     */
    @Override
    public UUID getCreatorUuid() {
        return this.creatorUuid;
    }

    /**
     * Setter for <code>public.namespace.creator_uuid</code>.
     */
    @Override
    public Namespace setCreatorUuid(UUID creatorUuid) {
        this.creatorUuid = creatorUuid;
        return this;
    }

    /**
     * Getter for <code>public.namespace.edited</code>.
     */
    @Override
    public LocalDateTime getEdited() {
        return this.edited;
    }

    /**
     * Setter for <code>public.namespace.edited</code>.
     */
    @Override
    public Namespace setEdited(LocalDateTime edited) {
        this.edited = edited;
        return this;
    }

    /**
     * Getter for <code>public.namespace.editor_uuid</code>.
     */
    @Override
    public UUID getEditorUuid() {
        return this.editorUuid;
    }

    /**
     * Setter for <code>public.namespace.editor_uuid</code>.
     */
    @Override
    public Namespace setEditorUuid(UUID editorUuid) {
        this.editorUuid = editorUuid;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Namespace (");

        sb.append(uuid);
        sb.append(", ").append(name);
        sb.append(", ").append(rootContentUuid);
        sb.append(", ").append(meta);
        sb.append(", ").append(pathPrefix);
        sb.append(", ").append(modelFilters);
        sb.append(", ").append(created);
        sb.append(", ").append(creatorUuid);
        sb.append(", ").append(edited);
        sb.append(", ").append(editorUuid);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(INamespace from) {
        setUuid(from.getUuid());
        setName(from.getName());
        setRootContentUuid(from.getRootContentUuid());
        setMeta(from.getMeta());
        setPathPrefix(from.getPathPrefix());
        setModelFilters(from.getModelFilters());
        setCreated(from.getCreated());
        setCreatorUuid(from.getCreatorUuid());
        setEdited(from.getEdited());
        setEditorUuid(from.getEditorUuid());
    }

    @Override
    public <E extends INamespace> E into(E into) {
        into.from(this);
        return into;
    }
}
