/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;
import io.metaloom.loom.db.jooq.tables.interfaces.IAssetUserMeta;

import java.util.UUID;


import static io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssetUserMeta implements VertxPojo, IAssetUserMeta {

    private static final long serialVersionUID = 1L;

    private UUID    assetUuid;
    private UUID    userUuid;
    private Integer rating;
    private String  meta;

    public AssetUserMeta() {}

    public AssetUserMeta(IAssetUserMeta value) {
        this.assetUuid = value.getAssetUuid();
        this.userUuid = value.getUserUuid();
        this.rating = value.getRating();
        this.meta = value.getMeta();
    }

    public AssetUserMeta(
        UUID    assetUuid,
        UUID    userUuid,
        Integer rating,
        String  meta
    ) {
        this.assetUuid = assetUuid;
        this.userUuid = userUuid;
        this.rating = rating;
        this.meta = meta;
    }

        public AssetUserMeta(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }

    /**
     * Getter for <code>public.asset_user_meta.asset_uuid</code>.
     */
    @Override
    public UUID getAssetUuid() {
        return this.assetUuid;
    }

    /**
     * Setter for <code>public.asset_user_meta.asset_uuid</code>.
     */
    @Override
    public AssetUserMeta setAssetUuid(UUID assetUuid) {
        this.assetUuid = assetUuid;
        return this;
    }

    /**
     * Getter for <code>public.asset_user_meta.user_uuid</code>.
     */
    @Override
    public UUID getUserUuid() {
        return this.userUuid;
    }

    /**
     * Setter for <code>public.asset_user_meta.user_uuid</code>.
     */
    @Override
    public AssetUserMeta setUserUuid(UUID userUuid) {
        this.userUuid = userUuid;
        return this;
    }

    /**
     * Getter for <code>public.asset_user_meta.rating</code>. Asset rating by the user
     */
    @Override
    public Integer getRating() {
        return this.rating;
    }

    /**
     * Setter for <code>public.asset_user_meta.rating</code>. Asset rating by the user
     */
    @Override
    public AssetUserMeta setRating(Integer rating) {
        this.rating = rating;
        return this;
    }

    /**
     * Getter for <code>public.asset_user_meta.meta</code>. Custom meta properties
     */
    @Override
    public String getMeta() {
        return this.meta;
    }

    /**
     * Setter for <code>public.asset_user_meta.meta</code>. Custom meta properties
     */
    @Override
    public AssetUserMeta setMeta(String meta) {
        this.meta = meta;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AssetUserMeta (");

        sb.append(assetUuid);
        sb.append(", ").append(userUuid);
        sb.append(", ").append(rating);
        sb.append(", ").append(meta);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IAssetUserMeta from) {
        setAssetUuid(from.getAssetUuid());
        setUserUuid(from.getUserUuid());
        setRating(from.getRating());
        setMeta(from.getMeta());
    }

    @Override
    public <E extends IAssetUserMeta> E into(E into) {
        into.from(this);
        return into;
    }
}
