/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * Store tag &lt;-&gt; collection reference
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqTagCollection implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID tagUuid;
    private UUID collectionUuid;

    public JooqTagCollection() {}

    public JooqTagCollection(JooqTagCollection value) {
        this.tagUuid = value.tagUuid;
        this.collectionUuid = value.collectionUuid;
    }

    public JooqTagCollection(
        UUID tagUuid,
        UUID collectionUuid
    ) {
        this.tagUuid = tagUuid;
        this.collectionUuid = collectionUuid;
    }

    /**
     * Getter for <code>public.tag_collection.tag_uuid</code>.
     */
    public UUID getTagUuid() {
        return this.tagUuid;
    }

    /**
     * Setter for <code>public.tag_collection.tag_uuid</code>.
     */
    public void setTagUuid(UUID tagUuid) {
        this.tagUuid = tagUuid;
    }

    /**
     * Getter for <code>public.tag_collection.collection_uuid</code>.
     */
    public UUID getCollectionUuid() {
        return this.collectionUuid;
    }

    /**
     * Setter for <code>public.tag_collection.collection_uuid</code>.
     */
    public void setCollectionUuid(UUID collectionUuid) {
        this.collectionUuid = collectionUuid;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final JooqTagCollection other = (JooqTagCollection) obj;
        if (this.tagUuid == null) {
            if (other.tagUuid != null)
                return false;
        }
        else if (!this.tagUuid.equals(other.tagUuid))
            return false;
        if (this.collectionUuid == null) {
            if (other.collectionUuid != null)
                return false;
        }
        else if (!this.collectionUuid.equals(other.collectionUuid))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.tagUuid == null) ? 0 : this.tagUuid.hashCode());
        result = prime * result + ((this.collectionUuid == null) ? 0 : this.collectionUuid.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JooqTagCollection (");

        sb.append(tagUuid);
        sb.append(", ").append(collectionUuid);

        sb.append(")");
        return sb.toString();
    }
}
