/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.pojos;


import io.metaloom.loom.db.jooq.enums.JooqLoomPermission;

import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqTokenPermission implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID tokenUuid;
    private String resource;
    private JooqLoomPermission permission;

    public JooqTokenPermission() {}

    public JooqTokenPermission(JooqTokenPermission value) {
        this.tokenUuid = value.tokenUuid;
        this.resource = value.resource;
        this.permission = value.permission;
    }

    public JooqTokenPermission(
        UUID tokenUuid,
        String resource,
        JooqLoomPermission permission
    ) {
        this.tokenUuid = tokenUuid;
        this.resource = resource;
        this.permission = permission;
    }

    /**
     * Getter for <code>public.token_permission.token_uuid</code>.
     */
    public UUID getTokenUuid() {
        return this.tokenUuid;
    }

    /**
     * Setter for <code>public.token_permission.token_uuid</code>.
     */
    public void setTokenUuid(UUID tokenUuid) {
        this.tokenUuid = tokenUuid;
    }

    /**
     * Getter for <code>public.token_permission.resource</code>.
     */
    public String getResource() {
        return this.resource;
    }

    /**
     * Setter for <code>public.token_permission.resource</code>.
     */
    public void setResource(String resource) {
        this.resource = resource;
    }

    /**
     * Getter for <code>public.token_permission.permission</code>. Permission
     * granted / granted to the resource
     */
    public JooqLoomPermission getPermission() {
        return this.permission;
    }

    /**
     * Setter for <code>public.token_permission.permission</code>. Permission
     * granted / granted to the resource
     */
    public void setPermission(JooqLoomPermission permission) {
        this.permission = permission;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final JooqTokenPermission other = (JooqTokenPermission) obj;
        if (this.tokenUuid == null) {
            if (other.tokenUuid != null)
                return false;
        }
        else if (!this.tokenUuid.equals(other.tokenUuid))
            return false;
        if (this.resource == null) {
            if (other.resource != null)
                return false;
        }
        else if (!this.resource.equals(other.resource))
            return false;
        if (this.permission == null) {
            if (other.permission != null)
                return false;
        }
        else if (!this.permission.equals(other.permission))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.tokenUuid == null) ? 0 : this.tokenUuid.hashCode());
        result = prime * result + ((this.resource == null) ? 0 : this.resource.hashCode());
        result = prime * result + ((this.permission == null) ? 0 : this.permission.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JooqTokenPermission (");

        sb.append(tokenUuid);
        sb.append(", ").append(resource);
        sb.append(", ").append(permission);

        sb.append(")");
        return sb.toString();
    }
}
