/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqTaskAnnotation implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID taskUuid;
    private UUID annotationUuid;

    public JooqTaskAnnotation() {}

    public JooqTaskAnnotation(JooqTaskAnnotation value) {
        this.taskUuid = value.taskUuid;
        this.annotationUuid = value.annotationUuid;
    }

    public JooqTaskAnnotation(
        UUID taskUuid,
        UUID annotationUuid
    ) {
        this.taskUuid = taskUuid;
        this.annotationUuid = annotationUuid;
    }

    /**
     * Getter for <code>public.task_annotation.task_uuid</code>.
     */
    public UUID getTaskUuid() {
        return this.taskUuid;
    }

    /**
     * Setter for <code>public.task_annotation.task_uuid</code>.
     */
    public void setTaskUuid(UUID taskUuid) {
        this.taskUuid = taskUuid;
    }

    /**
     * Getter for <code>public.task_annotation.annotation_uuid</code>.
     */
    public UUID getAnnotationUuid() {
        return this.annotationUuid;
    }

    /**
     * Setter for <code>public.task_annotation.annotation_uuid</code>.
     */
    public void setAnnotationUuid(UUID annotationUuid) {
        this.annotationUuid = annotationUuid;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final JooqTaskAnnotation other = (JooqTaskAnnotation) obj;
        if (this.taskUuid == null) {
            if (other.taskUuid != null)
                return false;
        }
        else if (!this.taskUuid.equals(other.taskUuid))
            return false;
        if (this.annotationUuid == null) {
            if (other.annotationUuid != null)
                return false;
        }
        else if (!this.annotationUuid.equals(other.annotationUuid))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.taskUuid == null) ? 0 : this.taskUuid.hashCode());
        result = prime * result + ((this.annotationUuid == null) ? 0 : this.annotationUuid.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JooqTaskAnnotation (");

        sb.append(taskUuid);
        sb.append(", ").append(annotationUuid);

        sb.append(")");
        return sb.toString();
    }
}
