/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqAnnotationTag implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID annotationUuid;
    private UUID tagUuid;

    public JooqAnnotationTag() {}

    public JooqAnnotationTag(JooqAnnotationTag value) {
        this.annotationUuid = value.annotationUuid;
        this.tagUuid = value.tagUuid;
    }

    public JooqAnnotationTag(
        UUID annotationUuid,
        UUID tagUuid
    ) {
        this.annotationUuid = annotationUuid;
        this.tagUuid = tagUuid;
    }

    /**
     * Getter for <code>public.annotation_tag.annotation_uuid</code>.
     */
    public UUID getAnnotationUuid() {
        return this.annotationUuid;
    }

    /**
     * Setter for <code>public.annotation_tag.annotation_uuid</code>.
     */
    public void setAnnotationUuid(UUID annotationUuid) {
        this.annotationUuid = annotationUuid;
    }

    /**
     * Getter for <code>public.annotation_tag.tag_uuid</code>.
     */
    public UUID getTagUuid() {
        return this.tagUuid;
    }

    /**
     * Setter for <code>public.annotation_tag.tag_uuid</code>.
     */
    public void setTagUuid(UUID tagUuid) {
        this.tagUuid = tagUuid;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final JooqAnnotationTag other = (JooqAnnotationTag) obj;
        if (this.annotationUuid == null) {
            if (other.annotationUuid != null)
                return false;
        }
        else if (!this.annotationUuid.equals(other.annotationUuid))
            return false;
        if (this.tagUuid == null) {
            if (other.tagUuid != null)
                return false;
        }
        else if (!this.tagUuid.equals(other.tagUuid))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.annotationUuid == null) ? 0 : this.annotationUuid.hashCode());
        result = prime * result + ((this.tagUuid == null) ? 0 : this.tagUuid.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JooqAnnotationTag (");

        sb.append(annotationUuid);
        sb.append(", ").append(tagUuid);

        sb.append(")");
        return sb.toString();
    }
}
