/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagAsset implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID tagUuid;
    private UUID assetUuid;

    public TagAsset() {}

    public TagAsset(TagAsset value) {
        this.tagUuid = value.tagUuid;
        this.assetUuid = value.assetUuid;
    }

    public TagAsset(
        UUID tagUuid,
        UUID assetUuid
    ) {
        this.tagUuid = tagUuid;
        this.assetUuid = assetUuid;
    }

    /**
     * Getter for <code>public.tag_asset.tag_uuid</code>.
     */
    public UUID getTagUuid() {
        return this.tagUuid;
    }

    /**
     * Setter for <code>public.tag_asset.tag_uuid</code>.
     */
    public void setTagUuid(UUID tagUuid) {
        this.tagUuid = tagUuid;
    }

    /**
     * Getter for <code>public.tag_asset.asset_uuid</code>.
     */
    public UUID getAssetUuid() {
        return this.assetUuid;
    }

    /**
     * Setter for <code>public.tag_asset.asset_uuid</code>.
     */
    public void setAssetUuid(UUID assetUuid) {
        this.assetUuid = assetUuid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TagAsset (");

        sb.append(tagUuid);
        sb.append(", ").append(assetUuid);

        sb.append(")");
        return sb.toString();
    }
}
