/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.util.UUID;


import static io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IModelVersion extends VertxPojo, Serializable {

    /**
     * Setter for <code>public.model_version.uuid</code>.
     */
    public IModelVersion setUuid(UUID value);

    /**
     * Getter for <code>public.model_version.uuid</code>.
     */
    public UUID getUuid();

    /**
     * Setter for <code>public.model_version.model_uuid</code>.
     */
    public IModelVersion setModelUuid(UUID value);

    /**
     * Getter for <code>public.model_version.model_uuid</code>.
     */
    public UUID getModelUuid();

    /**
     * Setter for <code>public.model_version.json</code>.
     */
    public IModelVersion setJson(String value);

    /**
     * Getter for <code>public.model_version.json</code>.
     */
    public String getJson();

    /**
     * Setter for <code>public.model_version.next_version_uuid</code>.
     */
    public IModelVersion setNextVersionUuid(UUID value);

    /**
     * Getter for <code>public.model_version.next_version_uuid</code>.
     */
    public UUID getNextVersionUuid();

    /**
     * Setter for <code>public.model_version.prev_version_uuid</code>.
     */
    public IModelVersion setPrevVersionUuid(UUID value);

    /**
     * Getter for <code>public.model_version.prev_version_uuid</code>.
     */
    public UUID getPrevVersionUuid();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IModelVersion
     */
    public void from(IModelVersion from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IModelVersion
     */
    public <E extends IModelVersion> E into(E into);

        @Override
        public default IModelVersion fromJson(io.vertx.core.json.JsonObject json) {
                // Omitting unrecognized type java.util.UUID for column uuid!
                // Omitting unrecognized type java.util.UUID for column model_uuid!
                setOrThrow(this::setJson,json::getString,"json","java.lang.String");
                // Omitting unrecognized type java.util.UUID for column next_version_uuid!
                // Omitting unrecognized type java.util.UUID for column prev_version_uuid!
                return this;
        }


        @Override
        public default io.vertx.core.json.JsonObject toJson() {
                io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
                // Omitting unrecognized type java.util.UUID for column uuid!
                // Omitting unrecognized type java.util.UUID for column model_uuid!
                json.put("json",getJson());
                // Omitting unrecognized type java.util.UUID for column next_version_uuid!
                // Omitting unrecognized type java.util.UUID for column prev_version_uuid!
                return json;
        }

}
