/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;


import static io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITag extends VertxPojo, Serializable {

    /**
     * Setter for <code>public.tag.uuid</code>.
     */
    public ITag setUuid(UUID value);

    /**
     * Getter for <code>public.tag.uuid</code>.
     */
    public UUID getUuid();

    /**
     * Setter for <code>public.tag.name</code>.
     */
    public ITag setName(String value);

    /**
     * Getter for <code>public.tag.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>public.tag.collection</code>.
     */
    public ITag setCollection(String value);

    /**
     * Getter for <code>public.tag.collection</code>.
     */
    public String getCollection();

    /**
     * Setter for <code>public.tag.namespace_uuid</code>.
     */
    public ITag setNamespaceUuid(UUID value);

    /**
     * Getter for <code>public.tag.namespace_uuid</code>.
     */
    public UUID getNamespaceUuid();

    /**
     * Setter for <code>public.tag.meta</code>. Custom meta properties to the element
     */
    public ITag setMeta(String value);

    /**
     * Getter for <code>public.tag.meta</code>. Custom meta properties to the element
     */
    public String getMeta();

    /**
     * Setter for <code>public.tag.rating</code>. Absolute or buffered/precomputed rating information
     */
    public ITag setRating(Integer value);

    /**
     * Getter for <code>public.tag.rating</code>. Absolute or buffered/precomputed rating information
     */
    public Integer getRating();

    /**
     * Setter for <code>public.tag.created</code>.
     */
    public ITag setCreated(LocalDateTime value);

    /**
     * Getter for <code>public.tag.created</code>.
     */
    public LocalDateTime getCreated();

    /**
     * Setter for <code>public.tag.creator_uuid</code>.
     */
    public ITag setCreatorUuid(UUID value);

    /**
     * Getter for <code>public.tag.creator_uuid</code>.
     */
    public UUID getCreatorUuid();

    /**
     * Setter for <code>public.tag.edited</code>.
     */
    public ITag setEdited(LocalDateTime value);

    /**
     * Getter for <code>public.tag.edited</code>.
     */
    public LocalDateTime getEdited();

    /**
     * Setter for <code>public.tag.editor_uuid</code>.
     */
    public ITag setEditorUuid(UUID value);

    /**
     * Getter for <code>public.tag.editor_uuid</code>.
     */
    public UUID getEditorUuid();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITag
     */
    public void from(ITag from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITag
     */
    public <E extends ITag> E into(E into);

        @Override
        public default ITag fromJson(io.vertx.core.json.JsonObject json) {
                // Omitting unrecognized type java.util.UUID for column uuid!
                setOrThrow(this::setName,json::getString,"name","java.lang.String");
                setOrThrow(this::setCollection,json::getString,"collection","java.lang.String");
                // Omitting unrecognized type java.util.UUID for column namespace_uuid!
                setOrThrow(this::setMeta,json::getString,"meta","java.lang.String");
                setOrThrow(this::setRating,json::getInteger,"rating","java.lang.Integer");
                setOrThrow(this::setCreated,key -> {String s = json.getString(key); return s==null?null:java.time.LocalDateTime.parse(s);},"created","java.time.LocalDateTime");
                // Omitting unrecognized type java.util.UUID for column creator_uuid!
                setOrThrow(this::setEdited,key -> {String s = json.getString(key); return s==null?null:java.time.LocalDateTime.parse(s);},"edited","java.time.LocalDateTime");
                // Omitting unrecognized type java.util.UUID for column editor_uuid!
                return this;
        }


        @Override
        public default io.vertx.core.json.JsonObject toJson() {
                io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
                // Omitting unrecognized type java.util.UUID for column uuid!
                json.put("name",getName());
                json.put("collection",getCollection());
                // Omitting unrecognized type java.util.UUID for column namespace_uuid!
                json.put("meta",getMeta());
                json.put("rating",getRating());
                json.put("created",getCreated()==null?null:getCreated().toString());
                // Omitting unrecognized type java.util.UUID for column creator_uuid!
                json.put("edited",getEdited()==null?null:getEdited().toString());
                // Omitting unrecognized type java.util.UUID for column editor_uuid!
                return json;
        }

}
