package io.metaloom.loom.db.model.perm;

public enum Permission {

	// Asset
	CREATE_ASSET, READ_ASSET, DELETE_ASSET, UPDATE_ASSET,
	
	// Asset Location
	CREATE_ASSET_LOCATION, READ_ASSET_LOCATION, DELETE_ASSET_LOCATION, UPDATE_ASSET_LOCATION,

	// User
	CREATE_USER, READ_USER, DELETE_USER, UPDATE_USER;
}
