/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.enums;


import io.metaloom.loom.db.jooq.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum EmbeddingTypes implements EnumType {

    DLIB_FACE_RESNET_v1("DLIB_FACE_RESNET_v1");

    private final String literal;

    private EmbeddingTypes(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "embedding_types";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static EmbeddingTypes lookupLiteral(String literal) {
        return EnumType.lookupLiteral(EmbeddingTypes.class, literal);
    }
}
