/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.enums;


import io.metaloom.loom.db.jooq.JooqPublic;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum JooqLoomPermission implements EnumType {

    CREATE_USER("CREATE_USER"),

    READ_USER("READ_USER"),

    UPDATE_USER("UPDATE_USER"),

    DELETE_USER("DELETE_USER"),

    CREATE_GROUP("CREATE_GROUP"),

    READ_GROUP("READ_GROUP"),

    UPDATE_GROUP("UPDATE_GROUP"),

    DELETE_GROUP("DELETE_GROUP"),

    CREATE_ROLE("CREATE_ROLE"),

    READ_ROLE("READ_ROLE"),

    UPDATE_ROLE("UPDATE_ROLE"),

    DELETE_ROLE("DELETE_ROLE"),

    CREATE_TAG("CREATE_TAG"),

    READ_TAG("READ_TAG"),

    UPDATE_TAG("UPDATE_TAG"),

    DELETE_TAG("DELETE_TAG"),

    CREATE_ASSET("CREATE_ASSET"),

    READ_ASSET("READ_ASSET"),

    UPDATE_ASSET("UPDATE_ASSET"),

    DELETE_ASSET("DELETE_ASSET"),

    UPLOAD_ASSET("UPLOAD_ASSET"),

    DOWNLOAD_ASSET("DOWNLOAD_ASSET"),

    LOCK_ASSET("LOCK_ASSET"),

    UNLOCK_ASSET("UNLOCK_ASSET"),

    CREATE_WEBHOOK("CREATE_WEBHOOK"),

    READ_WEBHOOK("READ_WEBHOOK"),

    UPDATE_WEBHOOK("UPDATE_WEBHOOK"),

    DELETE_WEBHOOK("DELETE_WEBHOOK");

    private final String literal;

    private JooqLoomPermission(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return JooqPublic.PUBLIC;
    }

    @Override
    public String getName() {
        return "loom_permission";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static JooqLoomPermission lookupLiteral(String literal) {
        return EnumType.lookupLiteral(JooqLoomPermission.class, literal);
    }
}
