/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables;


import io.metaloom.loom.db.jooq.JooqPublic;
import io.metaloom.loom.db.jooq.Keys;
import io.metaloom.loom.db.jooq.tables.records.JooqCommentTaskRecord;

import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqCommentTask extends TableImpl<JooqCommentTaskRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.comment_task</code>
     */
    public static final JooqCommentTask COMMENT_TASK = new JooqCommentTask();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JooqCommentTaskRecord> getRecordType() {
        return JooqCommentTaskRecord.class;
    }

    /**
     * The column <code>public.comment_task.comment_uuid</code>.
     */
    public final TableField<JooqCommentTaskRecord, UUID> COMMENT_UUID = createField(DSL.name("comment_uuid"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.comment_task.task_uuid</code>.
     */
    public final TableField<JooqCommentTaskRecord, UUID> TASK_UUID = createField(DSL.name("task_uuid"), SQLDataType.UUID.nullable(false), this, "");

    private JooqCommentTask(Name alias, Table<JooqCommentTaskRecord> aliased) {
        this(alias, aliased, null);
    }

    private JooqCommentTask(Name alias, Table<JooqCommentTaskRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.comment_task</code> table reference
     */
    public JooqCommentTask(String alias) {
        this(DSL.name(alias), COMMENT_TASK);
    }

    /**
     * Create an aliased <code>public.comment_task</code> table reference
     */
    public JooqCommentTask(Name alias) {
        this(alias, COMMENT_TASK);
    }

    /**
     * Create a <code>public.comment_task</code> table reference
     */
    public JooqCommentTask() {
        this(DSL.name("comment_task"), null);
    }

    public <O extends Record> JooqCommentTask(Table<O> child, ForeignKey<O, JooqCommentTaskRecord> key) {
        super(child, key, COMMENT_TASK);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : JooqPublic.PUBLIC;
    }

    @Override
    public UniqueKey<JooqCommentTaskRecord> getPrimaryKey() {
        return Keys.COMMENT_TASK_PKEY;
    }

    @Override
    public List<ForeignKey<JooqCommentTaskRecord, ?>> getReferences() {
        return Arrays.asList(Keys.COMMENT_TASK__COMMENT_TASK_COMMENT_UUID_FKEY, Keys.COMMENT_TASK__COMMENT_TASK_TASK_UUID_FKEY);
    }

    private transient JooqComment _comment;
    private transient JooqTask _task;

    /**
     * Get the implicit join path to the <code>public.comment</code> table.
     */
    public JooqComment comment() {
        if (_comment == null)
            _comment = new JooqComment(this, Keys.COMMENT_TASK__COMMENT_TASK_COMMENT_UUID_FKEY);

        return _comment;
    }

    /**
     * Get the implicit join path to the <code>public.task</code> table.
     */
    public JooqTask task() {
        if (_task == null)
            _task = new JooqTask(this, Keys.COMMENT_TASK__COMMENT_TASK_TASK_UUID_FKEY);

        return _task;
    }

    @Override
    public JooqCommentTask as(String alias) {
        return new JooqCommentTask(DSL.name(alias), this);
    }

    @Override
    public JooqCommentTask as(Name alias) {
        return new JooqCommentTask(alias, this);
    }

    @Override
    public JooqCommentTask as(Table<?> alias) {
        return new JooqCommentTask(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqCommentTask rename(String name) {
        return new JooqCommentTask(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqCommentTask rename(Name name) {
        return new JooqCommentTask(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqCommentTask rename(Table<?> name) {
        return new JooqCommentTask(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, UUID> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super UUID, ? super UUID, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super UUID, ? super UUID, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
