/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables;


import io.metaloom.loom.db.jooq.Indexes;
import io.metaloom.loom.db.jooq.JooqPublic;
import io.metaloom.loom.db.jooq.Keys;
import io.metaloom.loom.db.jooq.tables.records.JooqUserTokenRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function6;
import org.jooq.Index;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqUserToken extends TableImpl<JooqUserTokenRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.user_token</code>
     */
    public static final JooqUserToken USER_TOKEN = new JooqUserToken();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JooqUserTokenRecord> getRecordType() {
        return JooqUserTokenRecord.class;
    }

    /**
     * The column <code>public.user_token.uuid</code>.
     */
    public final TableField<JooqUserTokenRecord, java.util.UUID> UUID = createField(DSL.name("uuid"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field("uuid_generate_v4()", SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.user_token.user_uuid</code>.
     */
    public final TableField<JooqUserTokenRecord, java.util.UUID> USER_UUID = createField(DSL.name("user_uuid"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.user_token.description</code>.
     */
    public final TableField<JooqUserTokenRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.user_token.token</code>.
     */
    public final TableField<JooqUserTokenRecord, String> TOKEN = createField(DSL.name("token"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.user_token.created</code>.
     */
    public final TableField<JooqUserTokenRecord, LocalDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field("now()", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.user_token.meta</code>.
     */
    public final TableField<JooqUserTokenRecord, JSONB> META = createField(DSL.name("meta"), SQLDataType.JSONB, this, "");

    private JooqUserToken(Name alias, Table<JooqUserTokenRecord> aliased) {
        this(alias, aliased, null);
    }

    private JooqUserToken(Name alias, Table<JooqUserTokenRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.user_token</code> table reference
     */
    public JooqUserToken(String alias) {
        this(DSL.name(alias), USER_TOKEN);
    }

    /**
     * Create an aliased <code>public.user_token</code> table reference
     */
    public JooqUserToken(Name alias) {
        this(alias, USER_TOKEN);
    }

    /**
     * Create a <code>public.user_token</code> table reference
     */
    public JooqUserToken() {
        this(DSL.name("user_token"), null);
    }

    public <O extends Record> JooqUserToken(Table<O> child, ForeignKey<O, JooqUserTokenRecord> key) {
        super(child, key, USER_TOKEN);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : JooqPublic.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.USER_TOKEN_USER_UUID_IDX);
    }

    @Override
    public UniqueKey<JooqUserTokenRecord> getPrimaryKey() {
        return Keys.USER_TOKEN_PKEY;
    }

    @Override
    public List<ForeignKey<JooqUserTokenRecord, ?>> getReferences() {
        return Arrays.asList(Keys.USER_TOKEN__USER_TOKEN_USER_UUID_FKEY);
    }

    private transient JooqUser _user;

    /**
     * Get the implicit join path to the <code>public.user</code> table.
     */
    public JooqUser user() {
        if (_user == null)
            _user = new JooqUser(this, Keys.USER_TOKEN__USER_TOKEN_USER_UUID_FKEY);

        return _user;
    }

    @Override
    public JooqUserToken as(String alias) {
        return new JooqUserToken(DSL.name(alias), this);
    }

    @Override
    public JooqUserToken as(Name alias) {
        return new JooqUserToken(alias, this);
    }

    @Override
    public JooqUserToken as(Table<?> alias) {
        return new JooqUserToken(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqUserToken rename(String name) {
        return new JooqUserToken(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqUserToken rename(Name name) {
        return new JooqUserToken(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqUserToken rename(Table<?> name) {
        return new JooqUserToken(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<java.util.UUID, java.util.UUID, String, String, LocalDateTime, JSONB> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function6<? super java.util.UUID, ? super java.util.UUID, ? super String, ? super String, ? super LocalDateTime, ? super JSONB, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super java.util.UUID, ? super java.util.UUID, ? super String, ? super String, ? super LocalDateTime, ? super JSONB, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
