/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.daos;


import io.metaloom.loom.db.jooq.tables.JooqCollectionAsset;
import io.metaloom.loom.db.jooq.tables.records.JooqCollectionAssetRecord;

import java.util.List;
import java.util.UUID;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * Track assets that belong to a collection.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqCollectionAssetDao extends DAOImpl<JooqCollectionAssetRecord, io.metaloom.loom.db.jooq.tables.pojos.JooqCollectionAsset, Record2<UUID, UUID>> {

    /**
     * Create a new JooqCollectionAssetDao without any configuration
     */
    public JooqCollectionAssetDao() {
        super(JooqCollectionAsset.COLLECTION_ASSET, io.metaloom.loom.db.jooq.tables.pojos.JooqCollectionAsset.class);
    }

    /**
     * Create a new JooqCollectionAssetDao with an attached configuration
     */
    public JooqCollectionAssetDao(Configuration configuration) {
        super(JooqCollectionAsset.COLLECTION_ASSET, io.metaloom.loom.db.jooq.tables.pojos.JooqCollectionAsset.class, configuration);
    }

    @Override
    public Record2<UUID, UUID> getId(io.metaloom.loom.db.jooq.tables.pojos.JooqCollectionAsset object) {
        return compositeKeyRecord(object.getCollectionUuid(), object.getAssetUuid());
    }

    /**
     * Fetch records that have <code>collection_uuid BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<io.metaloom.loom.db.jooq.tables.pojos.JooqCollectionAsset> fetchRangeOfJooqCollectionUuid(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(JooqCollectionAsset.COLLECTION_ASSET.COLLECTION_UUID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>collection_uuid IN (values)</code>
     */
    public List<io.metaloom.loom.db.jooq.tables.pojos.JooqCollectionAsset> fetchByJooqCollectionUuid(UUID... values) {
        return fetch(JooqCollectionAsset.COLLECTION_ASSET.COLLECTION_UUID, values);
    }

    /**
     * Fetch records that have <code>asset_uuid BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<io.metaloom.loom.db.jooq.tables.pojos.JooqCollectionAsset> fetchRangeOfJooqAssetUuid(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(JooqCollectionAsset.COLLECTION_ASSET.ASSET_UUID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>asset_uuid IN (values)</code>
     */
    public List<io.metaloom.loom.db.jooq.tables.pojos.JooqCollectionAsset> fetchByJooqAssetUuid(UUID... values) {
        return fetch(JooqCollectionAsset.COLLECTION_ASSET.ASSET_UUID, values);
    }
}
