/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.daos;


import io.metaloom.loom.db.jooq.tables.RoleGroup;
import io.metaloom.loom.db.jooq.tables.pojos.JooqRoleGroup;
import io.metaloom.loom.db.jooq.tables.records.RoleGroupRecord;

import java.util.List;
import java.util.UUID;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqRoleGroupDao extends DAOImpl<RoleGroupRecord, JooqRoleGroup, Record2<UUID, UUID>> {

    /**
     * Create a new JooqRoleGroupDao without any configuration
     */
    public JooqRoleGroupDao() {
        super(RoleGroup.ROLE_GROUP, JooqRoleGroup.class);
    }

    /**
     * Create a new JooqRoleGroupDao with an attached configuration
     */
    public JooqRoleGroupDao(Configuration configuration) {
        super(RoleGroup.ROLE_GROUP, JooqRoleGroup.class, configuration);
    }

    @Override
    public Record2<UUID, UUID> getId(JooqRoleGroup object) {
        return compositeKeyRecord(object.getGroupUuid(), object.getRoleUuid());
    }

    /**
     * Fetch records that have <code>group_uuid BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<JooqRoleGroup> fetchRangeOfGroupUuid(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(RoleGroup.ROLE_GROUP.GROUP_UUID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>group_uuid IN (values)</code>
     */
    public List<JooqRoleGroup> fetchByGroupUuid(UUID... values) {
        return fetch(RoleGroup.ROLE_GROUP.GROUP_UUID, values);
    }

    /**
     * Fetch records that have <code>role_uuid BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<JooqRoleGroup> fetchRangeOfRoleUuid(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(RoleGroup.ROLE_GROUP.ROLE_UUID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>role_uuid IN (values)</code>
     */
    public List<JooqRoleGroup> fetchByRoleUuid(UUID... values) {
        return fetch(RoleGroup.ROLE_GROUP.ROLE_UUID, values);
    }
}
