/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.daos;


import io.metaloom.loom.db.jooq.enums.LoomPermission;
import io.metaloom.loom.db.jooq.tables.UserPermission;
import io.metaloom.loom.db.jooq.tables.pojos.JooqUserPermission;
import io.metaloom.loom.db.jooq.tables.records.UserPermissionRecord;

import java.util.List;
import java.util.UUID;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqUserPermissionDao extends DAOImpl<UserPermissionRecord, JooqUserPermission, Record2<UUID, String>> {

    /**
     * Create a new JooqUserPermissionDao without any configuration
     */
    public JooqUserPermissionDao() {
        super(UserPermission.USER_PERMISSION, JooqUserPermission.class);
    }

    /**
     * Create a new JooqUserPermissionDao with an attached configuration
     */
    public JooqUserPermissionDao(Configuration configuration) {
        super(UserPermission.USER_PERMISSION, JooqUserPermission.class, configuration);
    }

    @Override
    public Record2<UUID, String> getId(JooqUserPermission object) {
        return compositeKeyRecord(object.getUserUuid(), object.getResource());
    }

    /**
     * Fetch records that have <code>user_uuid BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<JooqUserPermission> fetchRangeOfUserUuid(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(UserPermission.USER_PERMISSION.USER_UUID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_uuid IN (values)</code>
     */
    public List<JooqUserPermission> fetchByUserUuid(UUID... values) {
        return fetch(UserPermission.USER_PERMISSION.USER_UUID, values);
    }

    /**
     * Fetch records that have <code>resource BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<JooqUserPermission> fetchRangeOfResource(String lowerInclusive, String upperInclusive) {
        return fetchRange(UserPermission.USER_PERMISSION.RESOURCE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>resource IN (values)</code>
     */
    public List<JooqUserPermission> fetchByResource(String... values) {
        return fetch(UserPermission.USER_PERMISSION.RESOURCE, values);
    }

    /**
     * Fetch records that have <code>permission BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<JooqUserPermission> fetchRangeOfPermission(LoomPermission lowerInclusive, LoomPermission upperInclusive) {
        return fetchRange(UserPermission.USER_PERMISSION.PERMISSION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>permission IN (values)</code>
     */
    public List<JooqUserPermission> fetchByPermission(LoomPermission... values) {
        return fetch(UserPermission.USER_PERMISSION.PERMISSION, values);
    }
}
