/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.daos;


import io.metaloom.loom.db.jooq.tables.JooqUserGroup;
import io.metaloom.loom.db.jooq.tables.records.JooqUserGroupRecord;

import java.util.List;
import java.util.UUID;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqUserGroupDao extends DAOImpl<JooqUserGroupRecord, io.metaloom.loom.db.jooq.tables.pojos.JooqUserGroup, Record2<UUID, UUID>> {

    /**
     * Create a new JooqUserGroupDao without any configuration
     */
    public JooqUserGroupDao() {
        super(JooqUserGroup.USER_GROUP, io.metaloom.loom.db.jooq.tables.pojos.JooqUserGroup.class);
    }

    /**
     * Create a new JooqUserGroupDao with an attached configuration
     */
    public JooqUserGroupDao(Configuration configuration) {
        super(JooqUserGroup.USER_GROUP, io.metaloom.loom.db.jooq.tables.pojos.JooqUserGroup.class, configuration);
    }

    @Override
    public Record2<UUID, UUID> getId(io.metaloom.loom.db.jooq.tables.pojos.JooqUserGroup object) {
        return compositeKeyRecord(object.getUserUuid(), object.getGroupUuid());
    }

    /**
     * Fetch records that have <code>user_uuid BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<io.metaloom.loom.db.jooq.tables.pojos.JooqUserGroup> fetchRangeOfJooqUserUuid(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(JooqUserGroup.USER_GROUP.USER_UUID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_uuid IN (values)</code>
     */
    public List<io.metaloom.loom.db.jooq.tables.pojos.JooqUserGroup> fetchByJooqUserUuid(UUID... values) {
        return fetch(JooqUserGroup.USER_GROUP.USER_UUID, values);
    }

    /**
     * Fetch records that have <code>group_uuid BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<io.metaloom.loom.db.jooq.tables.pojos.JooqUserGroup> fetchRangeOfJooqGroupUuid(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(JooqUserGroup.USER_GROUP.GROUP_UUID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>group_uuid IN (values)</code>
     */
    public List<io.metaloom.loom.db.jooq.tables.pojos.JooqUserGroup> fetchByJooqGroupUuid(UUID... values) {
        return fetch(JooqUserGroup.USER_GROUP.GROUP_UUID, values);
    }
}
