/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.daos;


import io.metaloom.loom.db.jooq.enums.LoomPermission;
import io.metaloom.loom.db.jooq.tables.TokenPermission;
import io.metaloom.loom.db.jooq.tables.pojos.JooqTokenPermission;
import io.metaloom.loom.db.jooq.tables.records.TokenPermissionRecord;

import java.util.List;
import java.util.UUID;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqTokenPermissionDao extends DAOImpl<TokenPermissionRecord, JooqTokenPermission, Record2<UUID, String>> {

    /**
     * Create a new JooqTokenPermissionDao without any configuration
     */
    public JooqTokenPermissionDao() {
        super(TokenPermission.TOKEN_PERMISSION, JooqTokenPermission.class);
    }

    /**
     * Create a new JooqTokenPermissionDao with an attached configuration
     */
    public JooqTokenPermissionDao(Configuration configuration) {
        super(TokenPermission.TOKEN_PERMISSION, JooqTokenPermission.class, configuration);
    }

    @Override
    public Record2<UUID, String> getId(JooqTokenPermission object) {
        return compositeKeyRecord(object.getTokenUuid(), object.getResource());
    }

    /**
     * Fetch records that have <code>token_uuid BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<JooqTokenPermission> fetchRangeOfTokenUuid(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(TokenPermission.TOKEN_PERMISSION.TOKEN_UUID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>token_uuid IN (values)</code>
     */
    public List<JooqTokenPermission> fetchByTokenUuid(UUID... values) {
        return fetch(TokenPermission.TOKEN_PERMISSION.TOKEN_UUID, values);
    }

    /**
     * Fetch records that have <code>resource BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<JooqTokenPermission> fetchRangeOfResource(String lowerInclusive, String upperInclusive) {
        return fetchRange(TokenPermission.TOKEN_PERMISSION.RESOURCE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>resource IN (values)</code>
     */
    public List<JooqTokenPermission> fetchByResource(String... values) {
        return fetch(TokenPermission.TOKEN_PERMISSION.RESOURCE, values);
    }

    /**
     * Fetch records that have <code>permission BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<JooqTokenPermission> fetchRangeOfPermission(LoomPermission lowerInclusive, LoomPermission upperInclusive) {
        return fetchRange(TokenPermission.TOKEN_PERMISSION.PERMISSION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>permission IN (values)</code>
     */
    public List<JooqTokenPermission> fetchByPermission(LoomPermission... values) {
        return fetch(TokenPermission.TOKEN_PERMISSION.PERMISSION, values);
    }
}
