/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables;


import io.metaloom.loom.db.jooq.Keys;
import io.metaloom.loom.db.jooq.Public;
import io.metaloom.loom.db.jooq.tables.records.RoleGroupRecord;

import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoleGroup extends TableImpl<RoleGroupRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.role_group</code>
     */
    public static final RoleGroup ROLE_GROUP = new RoleGroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RoleGroupRecord> getRecordType() {
        return RoleGroupRecord.class;
    }

    /**
     * The column <code>public.role_group.group_uuid</code>.
     */
    public final TableField<RoleGroupRecord, UUID> GROUP_UUID = createField(DSL.name("group_uuid"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.role_group.role_uuid</code>.
     */
    public final TableField<RoleGroupRecord, UUID> ROLE_UUID = createField(DSL.name("role_uuid"), SQLDataType.UUID.nullable(false), this, "");

    private RoleGroup(Name alias, Table<RoleGroupRecord> aliased) {
        this(alias, aliased, null);
    }

    private RoleGroup(Name alias, Table<RoleGroupRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.role_group</code> table reference
     */
    public RoleGroup(String alias) {
        this(DSL.name(alias), ROLE_GROUP);
    }

    /**
     * Create an aliased <code>public.role_group</code> table reference
     */
    public RoleGroup(Name alias) {
        this(alias, ROLE_GROUP);
    }

    /**
     * Create a <code>public.role_group</code> table reference
     */
    public RoleGroup() {
        this(DSL.name("role_group"), null);
    }

    public <O extends Record> RoleGroup(Table<O> child, ForeignKey<O, RoleGroupRecord> key) {
        super(child, key, ROLE_GROUP);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<RoleGroupRecord> getPrimaryKey() {
        return Keys.ROLE_GROUP_PKEY;
    }

    @Override
    public List<UniqueKey<RoleGroupRecord>> getKeys() {
        return Arrays.<UniqueKey<RoleGroupRecord>>asList(Keys.ROLE_GROUP_PKEY);
    }

    @Override
    public List<ForeignKey<RoleGroupRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RoleGroupRecord, ?>>asList(Keys.ROLE_GROUP__ROLE_GROUP_GROUP_UUID_FKEY, Keys.ROLE_GROUP__ROLE_GROUP_ROLE_UUID_FKEY);
    }

    private transient Group _group;
    private transient Role _role;

    public Group group() {
        if (_group == null)
            _group = new Group(this, Keys.ROLE_GROUP__ROLE_GROUP_GROUP_UUID_FKEY);

        return _group;
    }

    public Role role() {
        if (_role == null)
            _role = new Role(this, Keys.ROLE_GROUP__ROLE_GROUP_ROLE_UUID_FKEY);

        return _role;
    }

    @Override
    public RoleGroup as(String alias) {
        return new RoleGroup(DSL.name(alias), this);
    }

    @Override
    public RoleGroup as(Name alias) {
        return new RoleGroup(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RoleGroup rename(String name) {
        return new RoleGroup(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RoleGroup rename(Name name) {
        return new RoleGroup(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, UUID> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
