/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.records;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;
import io.metaloom.loom.db.jooq.tables.AssetTimelineTag;
import io.metaloom.loom.db.jooq.tables.interfaces.IAssetTimelineTag;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


import static io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssetTimelineTagRecord extends TableRecordImpl<AssetTimelineTagRecord> implements VertxPojo, Record2<UUID, UUID>, IAssetTimelineTag {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.asset_timeline_tag.assettimeline_uuid</code>.
     */
    @Override
    public AssetTimelineTagRecord setAssettimelineUuid(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.asset_timeline_tag.assettimeline_uuid</code>.
     */
    @Override
    public UUID getAssettimelineUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.asset_timeline_tag.tag_uuid</code>.
     */
    @Override
    public AssetTimelineTagRecord setTagUuid(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.asset_timeline_tag.tag_uuid</code>.
     */
    @Override
    public UUID getTagUuid() {
        return (UUID) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, UUID> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<UUID, UUID> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return AssetTimelineTag.ASSET_TIMELINE_TAG.ASSETTIMELINE_UUID;
    }

    @Override
    public Field<UUID> field2() {
        return AssetTimelineTag.ASSET_TIMELINE_TAG.TAG_UUID;
    }

    @Override
    public UUID component1() {
        return getAssettimelineUuid();
    }

    @Override
    public UUID component2() {
        return getTagUuid();
    }

    @Override
    public UUID value1() {
        return getAssettimelineUuid();
    }

    @Override
    public UUID value2() {
        return getTagUuid();
    }

    @Override
    public AssetTimelineTagRecord value1(UUID value) {
        setAssettimelineUuid(value);
        return this;
    }

    @Override
    public AssetTimelineTagRecord value2(UUID value) {
        setTagUuid(value);
        return this;
    }

    @Override
    public AssetTimelineTagRecord values(UUID value1, UUID value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IAssetTimelineTag from) {
        setAssettimelineUuid(from.getAssettimelineUuid());
        setTagUuid(from.getTagUuid());
    }

    @Override
    public <E extends IAssetTimelineTag> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AssetTimelineTagRecord
     */
    public AssetTimelineTagRecord() {
        super(AssetTimelineTag.ASSET_TIMELINE_TAG);
    }

    /**
     * Create a detached, initialised AssetTimelineTagRecord
     */
    public AssetTimelineTagRecord(UUID assettimelineUuid, UUID tagUuid) {
        super(AssetTimelineTag.ASSET_TIMELINE_TAG);

        setAssettimelineUuid(assettimelineUuid);
        setTagUuid(tagUuid);
    }

        public AssetTimelineTagRecord(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }
}
