/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.records;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;
import io.metaloom.loom.db.jooq.tables.AssetBinary;
import io.metaloom.loom.db.jooq.tables.interfaces.IAssetBinary;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


import static io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * This table stores the immutable asset information
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssetBinaryRecord extends UpdatableRecordImpl<AssetBinaryRecord> implements VertxPojo, Record8<UUID, String, Integer, String, String, Integer, Integer, String>, IAssetBinary {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.asset_binary.uuid</code>.
     */
    @Override
    public AssetBinaryRecord setUuid(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.asset_binary.uuid</code>.
     */
    @Override
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.asset_binary.sha512sum</code>.
     */
    @Override
    public AssetBinaryRecord setSha512sum(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.asset_binary.sha512sum</code>.
     */
    @Override
    public String getSha512sum() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.asset_binary.size</code>.
     */
    @Override
    public AssetBinaryRecord setSize(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.asset_binary.size</code>.
     */
    @Override
    public Integer getSize() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.asset_binary.sha256sum</code>.
     */
    @Override
    public AssetBinaryRecord setSha256sum(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.asset_binary.sha256sum</code>.
     */
    @Override
    public String getSha256sum() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.asset_binary.md5sum</code>.
     */
    @Override
    public AssetBinaryRecord setMd5sum(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.asset_binary.md5sum</code>.
     */
    @Override
    public String getMd5sum() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.asset_binary.media_width</code>. Only set for images
     */
    @Override
    public AssetBinaryRecord setMediaWidth(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.asset_binary.media_width</code>. Only set for images
     */
    @Override
    public Integer getMediaWidth() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.asset_binary.media_height</code>. Only set for images
     */
    @Override
    public AssetBinaryRecord setMediaHeight(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.asset_binary.media_height</code>. Only set for images
     */
    @Override
    public Integer getMediaHeight() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.asset_binary.fingerprint</code>. Media fingerprint information
     */
    @Override
    public AssetBinaryRecord setFingerprint(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.asset_binary.fingerprint</code>. Media fingerprint information
     */
    @Override
    public String getFingerprint() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<UUID, String, Integer, String, String, Integer, Integer, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<UUID, String, Integer, String, String, Integer, Integer, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return AssetBinary.ASSET_BINARY.UUID;
    }

    @Override
    public Field<String> field2() {
        return AssetBinary.ASSET_BINARY.SHA512SUM;
    }

    @Override
    public Field<Integer> field3() {
        return AssetBinary.ASSET_BINARY.SIZE;
    }

    @Override
    public Field<String> field4() {
        return AssetBinary.ASSET_BINARY.SHA256SUM;
    }

    @Override
    public Field<String> field5() {
        return AssetBinary.ASSET_BINARY.MD5SUM;
    }

    @Override
    public Field<Integer> field6() {
        return AssetBinary.ASSET_BINARY.MEDIA_WIDTH;
    }

    @Override
    public Field<Integer> field7() {
        return AssetBinary.ASSET_BINARY.MEDIA_HEIGHT;
    }

    @Override
    public Field<String> field8() {
        return AssetBinary.ASSET_BINARY.FINGERPRINT;
    }

    @Override
    public UUID component1() {
        return getUuid();
    }

    @Override
    public String component2() {
        return getSha512sum();
    }

    @Override
    public Integer component3() {
        return getSize();
    }

    @Override
    public String component4() {
        return getSha256sum();
    }

    @Override
    public String component5() {
        return getMd5sum();
    }

    @Override
    public Integer component6() {
        return getMediaWidth();
    }

    @Override
    public Integer component7() {
        return getMediaHeight();
    }

    @Override
    public String component8() {
        return getFingerprint();
    }

    @Override
    public UUID value1() {
        return getUuid();
    }

    @Override
    public String value2() {
        return getSha512sum();
    }

    @Override
    public Integer value3() {
        return getSize();
    }

    @Override
    public String value4() {
        return getSha256sum();
    }

    @Override
    public String value5() {
        return getMd5sum();
    }

    @Override
    public Integer value6() {
        return getMediaWidth();
    }

    @Override
    public Integer value7() {
        return getMediaHeight();
    }

    @Override
    public String value8() {
        return getFingerprint();
    }

    @Override
    public AssetBinaryRecord value1(UUID value) {
        setUuid(value);
        return this;
    }

    @Override
    public AssetBinaryRecord value2(String value) {
        setSha512sum(value);
        return this;
    }

    @Override
    public AssetBinaryRecord value3(Integer value) {
        setSize(value);
        return this;
    }

    @Override
    public AssetBinaryRecord value4(String value) {
        setSha256sum(value);
        return this;
    }

    @Override
    public AssetBinaryRecord value5(String value) {
        setMd5sum(value);
        return this;
    }

    @Override
    public AssetBinaryRecord value6(Integer value) {
        setMediaWidth(value);
        return this;
    }

    @Override
    public AssetBinaryRecord value7(Integer value) {
        setMediaHeight(value);
        return this;
    }

    @Override
    public AssetBinaryRecord value8(String value) {
        setFingerprint(value);
        return this;
    }

    @Override
    public AssetBinaryRecord values(UUID value1, String value2, Integer value3, String value4, String value5, Integer value6, Integer value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IAssetBinary from) {
        setUuid(from.getUuid());
        setSha512sum(from.getSha512sum());
        setSize(from.getSize());
        setSha256sum(from.getSha256sum());
        setMd5sum(from.getMd5sum());
        setMediaWidth(from.getMediaWidth());
        setMediaHeight(from.getMediaHeight());
        setFingerprint(from.getFingerprint());
    }

    @Override
    public <E extends IAssetBinary> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AssetBinaryRecord
     */
    public AssetBinaryRecord() {
        super(AssetBinary.ASSET_BINARY);
    }

    /**
     * Create a detached, initialised AssetBinaryRecord
     */
    public AssetBinaryRecord(UUID uuid, String sha512sum, Integer size, String sha256sum, String md5sum, Integer mediaWidth, Integer mediaHeight, String fingerprint) {
        super(AssetBinary.ASSET_BINARY);

        setUuid(uuid);
        setSha512sum(sha512sum);
        setSize(size);
        setSha256sum(sha256sum);
        setMd5sum(md5sum);
        setMediaWidth(mediaWidth);
        setMediaHeight(mediaHeight);
        setFingerprint(fingerprint);
    }

        public AssetBinaryRecord(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }
}
