/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.records;


import io.metaloom.loom.db.jooq.enums.LoomContentType;
import io.metaloom.loom.db.jooq.tables.FieldContent;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * Crosstable that tracks all fields for a content
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FieldContentRecord extends TableRecordImpl<FieldContentRecord> implements Record4<UUID, UUID, String, LoomContentType> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.field_content.fields_uuid</code>.
     */
    public void setFieldsUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.field_content.fields_uuid</code>.
     */
    public UUID getFieldsUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.field_content.content_uuid</code>.
     */
    public void setContentUuid(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.field_content.content_uuid</code>.
     */
    public UUID getContentUuid() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.field_content.webroot_path_info</code>. prefixed
     * with branch
     */
    public void setWebrootPathInfo(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.field_content.webroot_path_info</code>. prefixed
     * with branch
     */
    public String getWebrootPathInfo() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.field_content.content_type</code>. D or P for
     * draft and published
     */
    public void setContentType(LoomContentType value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.field_content.content_type</code>. D or P for
     * draft and published
     */
    public LoomContentType getContentType() {
        return (LoomContentType) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<UUID, UUID, String, LoomContentType> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<UUID, UUID, String, LoomContentType> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return FieldContent.FIELD_CONTENT.FIELDS_UUID;
    }

    @Override
    public Field<UUID> field2() {
        return FieldContent.FIELD_CONTENT.CONTENT_UUID;
    }

    @Override
    public Field<String> field3() {
        return FieldContent.FIELD_CONTENT.WEBROOT_PATH_INFO;
    }

    @Override
    public Field<LoomContentType> field4() {
        return FieldContent.FIELD_CONTENT.CONTENT_TYPE;
    }

    @Override
    public UUID component1() {
        return getFieldsUuid();
    }

    @Override
    public UUID component2() {
        return getContentUuid();
    }

    @Override
    public String component3() {
        return getWebrootPathInfo();
    }

    @Override
    public LoomContentType component4() {
        return getContentType();
    }

    @Override
    public UUID value1() {
        return getFieldsUuid();
    }

    @Override
    public UUID value2() {
        return getContentUuid();
    }

    @Override
    public String value3() {
        return getWebrootPathInfo();
    }

    @Override
    public LoomContentType value4() {
        return getContentType();
    }

    @Override
    public FieldContentRecord value1(UUID value) {
        setFieldsUuid(value);
        return this;
    }

    @Override
    public FieldContentRecord value2(UUID value) {
        setContentUuid(value);
        return this;
    }

    @Override
    public FieldContentRecord value3(String value) {
        setWebrootPathInfo(value);
        return this;
    }

    @Override
    public FieldContentRecord value4(LoomContentType value) {
        setContentType(value);
        return this;
    }

    @Override
    public FieldContentRecord values(UUID value1, UUID value2, String value3, LoomContentType value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FieldContentRecord
     */
    public FieldContentRecord() {
        super(FieldContent.FIELD_CONTENT);
    }

    /**
     * Create a detached, initialised FieldContentRecord
     */
    public FieldContentRecord(UUID fieldsUuid, UUID contentUuid, String webrootPathInfo, LoomContentType contentType) {
        super(FieldContent.FIELD_CONTENT);

        setFieldsUuid(fieldsUuid);
        setContentUuid(contentUuid);
        setWebrootPathInfo(webrootPathInfo);
        setContentType(contentType);
    }

    /**
     * Create a detached, initialised FieldContentRecord
     */
    public FieldContentRecord(io.metaloom.loom.db.jooq.tables.pojos.FieldContent value) {
        super(FieldContent.FIELD_CONTENT);

        if (value != null) {
            setFieldsUuid(value.getFieldsUuid());
            setContentUuid(value.getContentUuid());
            setWebrootPathInfo(value.getWebrootPathInfo());
            setContentType(value.getContentType());
        }
    }
}
