/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.records;


import io.metaloom.loom.db.jooq.tables.JooqAssetBinarie;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This table stores the immutable asset information
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqAssetBinarieRecord extends UpdatableRecordImpl<JooqAssetBinarieRecord> implements Record10<UUID, String, String, String, String, Long, Integer, Integer, Long, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.asset_binarie.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.asset_binarie.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.asset_binarie.sha512sum</code>.
     */
    public void setSha512sum(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.asset_binarie.sha512sum</code>.
     */
    public String getSha512sum() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.asset_binarie.sha256sum</code>.
     */
    public void setSha256sum(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.asset_binarie.sha256sum</code>.
     */
    public String getSha256sum() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.asset_binarie.chunkHash</code>.
     */
    public void setChunkhash(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.asset_binarie.chunkHash</code>.
     */
    public String getChunkhash() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.asset_binarie.md5sum</code>.
     */
    public void setMd5sum(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.asset_binarie.md5sum</code>.
     */
    public String getMd5sum() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.asset_binarie.size</code>.
     */
    public void setSize(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.asset_binarie.size</code>.
     */
    public Long getSize() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.asset_binarie.media_width</code>. Only set for
     * images
     */
    public void setMediaWidth(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.asset_binarie.media_width</code>. Only set for
     * images
     */
    public Integer getMediaWidth() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.asset_binarie.media_height</code>. Only set for
     * images
     */
    public void setMediaHeight(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.asset_binarie.media_height</code>. Only set for
     * images
     */
    public Integer getMediaHeight() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.asset_binarie.zero_chunk_count</code>.
     */
    public void setZeroChunkCount(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.asset_binarie.zero_chunk_count</code>.
     */
    public Long getZeroChunkCount() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.asset_binarie.fingerprint</code>. Media
     * fingerprint information
     */
    public void setFingerprint(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.asset_binarie.fingerprint</code>. Media
     * fingerprint information
     */
    public String getFingerprint() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<UUID, String, String, String, String, Long, Integer, Integer, Long, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<UUID, String, String, String, String, Long, Integer, Integer, Long, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return JooqAssetBinarie.ASSET_BINARIE.UUID;
    }

    @Override
    public Field<String> field2() {
        return JooqAssetBinarie.ASSET_BINARIE.SHA512SUM;
    }

    @Override
    public Field<String> field3() {
        return JooqAssetBinarie.ASSET_BINARIE.SHA256SUM;
    }

    @Override
    public Field<String> field4() {
        return JooqAssetBinarie.ASSET_BINARIE.CHUNKHASH;
    }

    @Override
    public Field<String> field5() {
        return JooqAssetBinarie.ASSET_BINARIE.MD5SUM;
    }

    @Override
    public Field<Long> field6() {
        return JooqAssetBinarie.ASSET_BINARIE.SIZE;
    }

    @Override
    public Field<Integer> field7() {
        return JooqAssetBinarie.ASSET_BINARIE.MEDIA_WIDTH;
    }

    @Override
    public Field<Integer> field8() {
        return JooqAssetBinarie.ASSET_BINARIE.MEDIA_HEIGHT;
    }

    @Override
    public Field<Long> field9() {
        return JooqAssetBinarie.ASSET_BINARIE.ZERO_CHUNK_COUNT;
    }

    @Override
    public Field<String> field10() {
        return JooqAssetBinarie.ASSET_BINARIE.FINGERPRINT;
    }

    @Override
    public UUID component1() {
        return getUuid();
    }

    @Override
    public String component2() {
        return getSha512sum();
    }

    @Override
    public String component3() {
        return getSha256sum();
    }

    @Override
    public String component4() {
        return getChunkhash();
    }

    @Override
    public String component5() {
        return getMd5sum();
    }

    @Override
    public Long component6() {
        return getSize();
    }

    @Override
    public Integer component7() {
        return getMediaWidth();
    }

    @Override
    public Integer component8() {
        return getMediaHeight();
    }

    @Override
    public Long component9() {
        return getZeroChunkCount();
    }

    @Override
    public String component10() {
        return getFingerprint();
    }

    @Override
    public UUID value1() {
        return getUuid();
    }

    @Override
    public String value2() {
        return getSha512sum();
    }

    @Override
    public String value3() {
        return getSha256sum();
    }

    @Override
    public String value4() {
        return getChunkhash();
    }

    @Override
    public String value5() {
        return getMd5sum();
    }

    @Override
    public Long value6() {
        return getSize();
    }

    @Override
    public Integer value7() {
        return getMediaWidth();
    }

    @Override
    public Integer value8() {
        return getMediaHeight();
    }

    @Override
    public Long value9() {
        return getZeroChunkCount();
    }

    @Override
    public String value10() {
        return getFingerprint();
    }

    @Override
    public JooqAssetBinarieRecord value1(UUID value) {
        setUuid(value);
        return this;
    }

    @Override
    public JooqAssetBinarieRecord value2(String value) {
        setSha512sum(value);
        return this;
    }

    @Override
    public JooqAssetBinarieRecord value3(String value) {
        setSha256sum(value);
        return this;
    }

    @Override
    public JooqAssetBinarieRecord value4(String value) {
        setChunkhash(value);
        return this;
    }

    @Override
    public JooqAssetBinarieRecord value5(String value) {
        setMd5sum(value);
        return this;
    }

    @Override
    public JooqAssetBinarieRecord value6(Long value) {
        setSize(value);
        return this;
    }

    @Override
    public JooqAssetBinarieRecord value7(Integer value) {
        setMediaWidth(value);
        return this;
    }

    @Override
    public JooqAssetBinarieRecord value8(Integer value) {
        setMediaHeight(value);
        return this;
    }

    @Override
    public JooqAssetBinarieRecord value9(Long value) {
        setZeroChunkCount(value);
        return this;
    }

    @Override
    public JooqAssetBinarieRecord value10(String value) {
        setFingerprint(value);
        return this;
    }

    @Override
    public JooqAssetBinarieRecord values(UUID value1, String value2, String value3, String value4, String value5, Long value6, Integer value7, Integer value8, Long value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JooqAssetBinarieRecord
     */
    public JooqAssetBinarieRecord() {
        super(JooqAssetBinarie.ASSET_BINARIE);
    }

    /**
     * Create a detached, initialised JooqAssetBinarieRecord
     */
    public JooqAssetBinarieRecord(UUID uuid, String sha512sum, String sha256sum, String chunkhash, String md5sum, Long size, Integer mediaWidth, Integer mediaHeight, Long zeroChunkCount, String fingerprint) {
        super(JooqAssetBinarie.ASSET_BINARIE);

        setUuid(uuid);
        setSha512sum(sha512sum);
        setSha256sum(sha256sum);
        setChunkhash(chunkhash);
        setMd5sum(md5sum);
        setSize(size);
        setMediaWidth(mediaWidth);
        setMediaHeight(mediaHeight);
        setZeroChunkCount(zeroChunkCount);
        setFingerprint(fingerprint);
    }

    /**
     * Create a detached, initialised JooqAssetBinarieRecord
     */
    public JooqAssetBinarieRecord(io.metaloom.loom.db.jooq.tables.pojos.JooqAssetBinarie value) {
        super(JooqAssetBinarie.ASSET_BINARIE);

        if (value != null) {
            setUuid(value.getUuid());
            setSha512sum(value.getSha512sum());
            setSha256sum(value.getSha256sum());
            setChunkhash(value.getChunkhash());
            setMd5sum(value.getMd5sum());
            setSize(value.getSize());
            setMediaWidth(value.getMediaWidth());
            setMediaHeight(value.getMediaHeight());
            setZeroChunkCount(value.getZeroChunkCount());
            setFingerprint(value.getFingerprint());
        }
    }
}
