/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.records;


import io.metaloom.loom.db.jooq.tables.JooqLanguage;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Table which stores the languages for loom
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqLanguageRecord extends UpdatableRecordImpl<JooqLanguageRecord> implements Record4<UUID, String, String, JSONB> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.language.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.language.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.language.native_name</code>.
     */
    public void setNativeName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.language.native_name</code>.
     */
    public String getNativeName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.language.tag</code>.
     */
    public void setTag(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.language.tag</code>.
     */
    public String getTag() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.language.meta</code>. Custom meta properties to
     * the element
     */
    public void setMeta(JSONB value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.language.meta</code>. Custom meta properties to
     * the element
     */
    public JSONB getMeta() {
        return (JSONB) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<UUID, String, String, JSONB> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<UUID, String, String, JSONB> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return JooqLanguage.LANGUAGE.UUID;
    }

    @Override
    public Field<String> field2() {
        return JooqLanguage.LANGUAGE.NATIVE_NAME;
    }

    @Override
    public Field<String> field3() {
        return JooqLanguage.LANGUAGE.TAG;
    }

    @Override
    public Field<JSONB> field4() {
        return JooqLanguage.LANGUAGE.META;
    }

    @Override
    public UUID component1() {
        return getUuid();
    }

    @Override
    public String component2() {
        return getNativeName();
    }

    @Override
    public String component3() {
        return getTag();
    }

    @Override
    public JSONB component4() {
        return getMeta();
    }

    @Override
    public UUID value1() {
        return getUuid();
    }

    @Override
    public String value2() {
        return getNativeName();
    }

    @Override
    public String value3() {
        return getTag();
    }

    @Override
    public JSONB value4() {
        return getMeta();
    }

    @Override
    public JooqLanguageRecord value1(UUID value) {
        setUuid(value);
        return this;
    }

    @Override
    public JooqLanguageRecord value2(String value) {
        setNativeName(value);
        return this;
    }

    @Override
    public JooqLanguageRecord value3(String value) {
        setTag(value);
        return this;
    }

    @Override
    public JooqLanguageRecord value4(JSONB value) {
        setMeta(value);
        return this;
    }

    @Override
    public JooqLanguageRecord values(UUID value1, String value2, String value3, JSONB value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JooqLanguageRecord
     */
    public JooqLanguageRecord() {
        super(JooqLanguage.LANGUAGE);
    }

    /**
     * Create a detached, initialised JooqLanguageRecord
     */
    public JooqLanguageRecord(UUID uuid, String nativeName, String tag, JSONB meta) {
        super(JooqLanguage.LANGUAGE);

        setUuid(uuid);
        setNativeName(nativeName);
        setTag(tag);
        setMeta(meta);
    }

    /**
     * Create a detached, initialised JooqLanguageRecord
     */
    public JooqLanguageRecord(io.metaloom.loom.db.jooq.tables.pojos.JooqLanguage value) {
        super(JooqLanguage.LANGUAGE);

        if (value != null) {
            setUuid(value.getUuid());
            setNativeName(value.getNativeName());
            setTag(value.getTag());
            setMeta(value.getMeta());
        }
    }
}
