/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.records;


import io.metaloom.loom.db.jooq.enums.JooqAnnotationType;
import io.metaloom.loom.db.jooq.tables.JooqAnnotation;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This table contains asset annotation entries which can be used to create
 * chapters or sections to assign tasks to.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqAnnotationRecord extends UpdatableRecordImpl<JooqAnnotationRecord> implements Record15<UUID, JooqAnnotationType, UUID, UUID, LocalDateTime, String, String, Integer, Integer, Integer, Integer, Integer, Integer, JSONB, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.annotation.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.annotation.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.annotation.type</code>.
     */
    public void setType(JooqAnnotationType value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.annotation.type</code>.
     */
    public JooqAnnotationType getType() {
        return (JooqAnnotationType) get(1);
    }

    /**
     * Setter for <code>public.annotation.asset_uuid</code>.
     */
    public void setAssetUuid(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.annotation.asset_uuid</code>.
     */
    public UUID getAssetUuid() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.annotation.creator_uuid</code>.
     */
    public void setCreatorUuid(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.annotation.creator_uuid</code>.
     */
    public UUID getCreatorUuid() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>public.annotation.created</code>. Creation timestamp
     */
    public void setCreated(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.annotation.created</code>. Creation timestamp
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.annotation.title</code>.
     */
    public void setTitle(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.annotation.title</code>.
     */
    public String getTitle() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.annotation.description</code>.
     */
    public void setDescription(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.annotation.description</code>.
     */
    public String getDescription() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.annotation.time_from</code>.
     */
    public void setTimeFrom(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.annotation.time_from</code>.
     */
    public Integer getTimeFrom() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.annotation.time_to</code>.
     */
    public void setTimeTo(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.annotation.time_to</code>.
     */
    public Integer getTimeTo() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.annotation.areaStartX</code>.
     */
    public void setAreastartx(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.annotation.areaStartX</code>.
     */
    public Integer getAreastartx() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.annotation.areaStartY</code>.
     */
    public void setAreastarty(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.annotation.areaStartY</code>.
     */
    public Integer getAreastarty() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.annotation.areaWidth</code>.
     */
    public void setAreawidth(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.annotation.areaWidth</code>.
     */
    public Integer getAreawidth() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>public.annotation.areaHeight</code>.
     */
    public void setAreaheight(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.annotation.areaHeight</code>.
     */
    public Integer getAreaheight() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>public.annotation.meta</code>. Custom meta properties
     */
    public void setMeta(JSONB value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.annotation.meta</code>. Custom meta properties
     */
    public JSONB getMeta() {
        return (JSONB) get(13);
    }

    /**
     * Setter for <code>public.annotation.thumbail</code>. Reference to the
     * thumbnail that depics the annotated element/area
     */
    public void setThumbail(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.annotation.thumbail</code>. Reference to the
     * thumbnail that depics the annotated element/area
     */
    public String getThumbail() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row15<UUID, JooqAnnotationType, UUID, UUID, LocalDateTime, String, String, Integer, Integer, Integer, Integer, Integer, Integer, JSONB, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    public Row15<UUID, JooqAnnotationType, UUID, UUID, LocalDateTime, String, String, Integer, Integer, Integer, Integer, Integer, Integer, JSONB, String> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return JooqAnnotation.ANNOTATION.UUID;
    }

    @Override
    public Field<JooqAnnotationType> field2() {
        return JooqAnnotation.ANNOTATION.TYPE;
    }

    @Override
    public Field<UUID> field3() {
        return JooqAnnotation.ANNOTATION.ASSET_UUID;
    }

    @Override
    public Field<UUID> field4() {
        return JooqAnnotation.ANNOTATION.CREATOR_UUID;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return JooqAnnotation.ANNOTATION.CREATED;
    }

    @Override
    public Field<String> field6() {
        return JooqAnnotation.ANNOTATION.TITLE;
    }

    @Override
    public Field<String> field7() {
        return JooqAnnotation.ANNOTATION.DESCRIPTION;
    }

    @Override
    public Field<Integer> field8() {
        return JooqAnnotation.ANNOTATION.TIME_FROM;
    }

    @Override
    public Field<Integer> field9() {
        return JooqAnnotation.ANNOTATION.TIME_TO;
    }

    @Override
    public Field<Integer> field10() {
        return JooqAnnotation.ANNOTATION.AREASTARTX;
    }

    @Override
    public Field<Integer> field11() {
        return JooqAnnotation.ANNOTATION.AREASTARTY;
    }

    @Override
    public Field<Integer> field12() {
        return JooqAnnotation.ANNOTATION.AREAWIDTH;
    }

    @Override
    public Field<Integer> field13() {
        return JooqAnnotation.ANNOTATION.AREAHEIGHT;
    }

    @Override
    public Field<JSONB> field14() {
        return JooqAnnotation.ANNOTATION.META;
    }

    @Override
    public Field<String> field15() {
        return JooqAnnotation.ANNOTATION.THUMBAIL;
    }

    @Override
    public UUID component1() {
        return getUuid();
    }

    @Override
    public JooqAnnotationType component2() {
        return getType();
    }

    @Override
    public UUID component3() {
        return getAssetUuid();
    }

    @Override
    public UUID component4() {
        return getCreatorUuid();
    }

    @Override
    public LocalDateTime component5() {
        return getCreated();
    }

    @Override
    public String component6() {
        return getTitle();
    }

    @Override
    public String component7() {
        return getDescription();
    }

    @Override
    public Integer component8() {
        return getTimeFrom();
    }

    @Override
    public Integer component9() {
        return getTimeTo();
    }

    @Override
    public Integer component10() {
        return getAreastartx();
    }

    @Override
    public Integer component11() {
        return getAreastarty();
    }

    @Override
    public Integer component12() {
        return getAreawidth();
    }

    @Override
    public Integer component13() {
        return getAreaheight();
    }

    @Override
    public JSONB component14() {
        return getMeta();
    }

    @Override
    public String component15() {
        return getThumbail();
    }

    @Override
    public UUID value1() {
        return getUuid();
    }

    @Override
    public JooqAnnotationType value2() {
        return getType();
    }

    @Override
    public UUID value3() {
        return getAssetUuid();
    }

    @Override
    public UUID value4() {
        return getCreatorUuid();
    }

    @Override
    public LocalDateTime value5() {
        return getCreated();
    }

    @Override
    public String value6() {
        return getTitle();
    }

    @Override
    public String value7() {
        return getDescription();
    }

    @Override
    public Integer value8() {
        return getTimeFrom();
    }

    @Override
    public Integer value9() {
        return getTimeTo();
    }

    @Override
    public Integer value10() {
        return getAreastartx();
    }

    @Override
    public Integer value11() {
        return getAreastarty();
    }

    @Override
    public Integer value12() {
        return getAreawidth();
    }

    @Override
    public Integer value13() {
        return getAreaheight();
    }

    @Override
    public JSONB value14() {
        return getMeta();
    }

    @Override
    public String value15() {
        return getThumbail();
    }

    @Override
    public JooqAnnotationRecord value1(UUID value) {
        setUuid(value);
        return this;
    }

    @Override
    public JooqAnnotationRecord value2(JooqAnnotationType value) {
        setType(value);
        return this;
    }

    @Override
    public JooqAnnotationRecord value3(UUID value) {
        setAssetUuid(value);
        return this;
    }

    @Override
    public JooqAnnotationRecord value4(UUID value) {
        setCreatorUuid(value);
        return this;
    }

    @Override
    public JooqAnnotationRecord value5(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public JooqAnnotationRecord value6(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public JooqAnnotationRecord value7(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public JooqAnnotationRecord value8(Integer value) {
        setTimeFrom(value);
        return this;
    }

    @Override
    public JooqAnnotationRecord value9(Integer value) {
        setTimeTo(value);
        return this;
    }

    @Override
    public JooqAnnotationRecord value10(Integer value) {
        setAreastartx(value);
        return this;
    }

    @Override
    public JooqAnnotationRecord value11(Integer value) {
        setAreastarty(value);
        return this;
    }

    @Override
    public JooqAnnotationRecord value12(Integer value) {
        setAreawidth(value);
        return this;
    }

    @Override
    public JooqAnnotationRecord value13(Integer value) {
        setAreaheight(value);
        return this;
    }

    @Override
    public JooqAnnotationRecord value14(JSONB value) {
        setMeta(value);
        return this;
    }

    @Override
    public JooqAnnotationRecord value15(String value) {
        setThumbail(value);
        return this;
    }

    @Override
    public JooqAnnotationRecord values(UUID value1, JooqAnnotationType value2, UUID value3, UUID value4, LocalDateTime value5, String value6, String value7, Integer value8, Integer value9, Integer value10, Integer value11, Integer value12, Integer value13, JSONB value14, String value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JooqAnnotationRecord
     */
    public JooqAnnotationRecord() {
        super(JooqAnnotation.ANNOTATION);
    }

    /**
     * Create a detached, initialised JooqAnnotationRecord
     */
    public JooqAnnotationRecord(UUID uuid, JooqAnnotationType type, UUID assetUuid, UUID creatorUuid, LocalDateTime created, String title, String description, Integer timeFrom, Integer timeTo, Integer areastartx, Integer areastarty, Integer areawidth, Integer areaheight, JSONB meta, String thumbail) {
        super(JooqAnnotation.ANNOTATION);

        setUuid(uuid);
        setType(type);
        setAssetUuid(assetUuid);
        setCreatorUuid(creatorUuid);
        setCreated(created);
        setTitle(title);
        setDescription(description);
        setTimeFrom(timeFrom);
        setTimeTo(timeTo);
        setAreastartx(areastartx);
        setAreastarty(areastarty);
        setAreawidth(areawidth);
        setAreaheight(areaheight);
        setMeta(meta);
        setThumbail(thumbail);
    }
}
