/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.records;


import io.metaloom.loom.db.jooq.tables.JooqAsset;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This table stores information on the asset component of the asset
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqAssetRecord extends UpdatableRecordImpl<JooqAssetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.asset.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.asset.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.asset.sha512sum</code>.
     */
    public void setSha512sum(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.asset.sha512sum</code>.
     */
    public String getSha512sum() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.asset.size</code>.
     */
    public void setSize(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.asset.size</code>.
     */
    public Long getSize() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.asset.sha256sum</code>.
     */
    public void setSha256sum(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.asset.sha256sum</code>.
     */
    public String getSha256sum() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.asset.md5sum</code>.
     */
    public void setMd5sum(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.asset.md5sum</code>.
     */
    public String getMd5sum() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.asset.chunk_hash</code>.
     */
    public void setChunkHash(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.asset.chunk_hash</code>.
     */
    public String getChunkHash() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.asset.zero_chunk_count</code>.
     */
    public void setZeroChunkCount(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.asset.zero_chunk_count</code>.
     */
    public Long getZeroChunkCount() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.asset.mime_type</code>.
     */
    public void setMimeType(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.asset.mime_type</code>.
     */
    public String getMimeType() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.asset.meta</code>. Custom meta properties to the
     * asset
     */
    public void setMeta(JSONB value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.asset.meta</code>. Custom meta properties to the
     * asset
     */
    public JSONB getMeta() {
        return (JSONB) get(8);
    }

    /**
     * Setter for <code>public.asset.author</code>.
     */
    public void setAuthor(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.asset.author</code>.
     */
    public String getAuthor() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.asset.geo_lon</code>.
     */
    public void setGeoLon(BigDecimal value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.asset.geo_lon</code>.
     */
    public BigDecimal getGeoLon() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>public.asset.geo_lat</code>.
     */
    public void setGeoLat(BigDecimal value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.asset.geo_lat</code>.
     */
    public BigDecimal getGeoLat() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for <code>public.asset.geo_alias</code>.
     */
    public void setGeoAlias(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.asset.geo_alias</code>.
     */
    public String getGeoAlias() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.asset.initial_origin</code>. Document the initial
     * origin of the asset (e.g. first filepath encountered, first s3 path, url,
     * hash)
     */
    public void setInitialOrigin(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.asset.initial_origin</code>. Document the initial
     * origin of the asset (e.g. first filepath encountered, first s3 path, url,
     * hash)
     */
    public String getInitialOrigin() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.asset.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.asset.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>public.asset.creator_uuid</code>.
     */
    public void setCreatorUuid(UUID value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.asset.creator_uuid</code>.
     */
    public UUID getCreatorUuid() {
        return (UUID) get(15);
    }

    /**
     * Setter for <code>public.asset.edited</code>.
     */
    public void setEdited(LocalDateTime value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.asset.edited</code>.
     */
    public LocalDateTime getEdited() {
        return (LocalDateTime) get(16);
    }

    /**
     * Setter for <code>public.asset.editor_uuid</code>.
     */
    public void setEditorUuid(UUID value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.asset.editor_uuid</code>.
     */
    public UUID getEditorUuid() {
        return (UUID) get(17);
    }

    /**
     * Setter for <code>public.asset.s3_bucket_name</code>.
     */
    public void setS3BucketName(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.asset.s3_bucket_name</code>.
     */
    public String getS3BucketName() {
        return (String) get(18);
    }

    /**
     * Setter for <code>public.asset.s3_object_path</code>.
     */
    public void setS3ObjectPath(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.asset.s3_object_path</code>.
     */
    public String getS3ObjectPath() {
        return (String) get(19);
    }

    /**
     * Setter for <code>public.asset.media_width</code>. Only set for images,
     * video
     */
    public void setMediaWidth(Integer value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.asset.media_width</code>. Only set for images,
     * video
     */
    public Integer getMediaWidth() {
        return (Integer) get(20);
    }

    /**
     * Setter for <code>public.asset.media_height</code>. Only set for images,
     * video
     */
    public void setMediaHeight(Integer value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.asset.media_height</code>. Only set for images,
     * video
     */
    public Integer getMediaHeight() {
        return (Integer) get(21);
    }

    /**
     * Setter for <code>public.asset.media_duration</code>. Duration of the
     * video, audio
     */
    public void setMediaDuration(Integer value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.asset.media_duration</code>. Duration of the
     * video, audio
     */
    public Integer getMediaDuration() {
        return (Integer) get(22);
    }

    /**
     * Setter for <code>public.asset.video_width</code>.
     */
    public void setVideoWidth(Integer value) {
        set(23, value);
    }

    /**
     * Getter for <code>public.asset.video_width</code>.
     */
    public Integer getVideoWidth() {
        return (Integer) get(23);
    }

    /**
     * Setter for <code>public.asset.video_height</code>.
     */
    public void setVideoHeight(Integer value) {
        set(24, value);
    }

    /**
     * Getter for <code>public.asset.video_height</code>.
     */
    public Integer getVideoHeight() {
        return (Integer) get(24);
    }

    /**
     * Setter for <code>public.asset.video_fingerprint</code>. Video fingerprint
     * information
     */
    public void setVideoFingerprint(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>public.asset.video_fingerprint</code>. Video fingerprint
     * information
     */
    public String getVideoFingerprint() {
        return (String) get(25);
    }

    /**
     * Setter for <code>public.asset.video_bitrate</code>.
     */
    public void setVideoBitrate(Integer value) {
        set(26, value);
    }

    /**
     * Getter for <code>public.asset.video_bitrate</code>.
     */
    public Integer getVideoBitrate() {
        return (Integer) get(26);
    }

    /**
     * Setter for <code>public.asset.video_encoding</code>.
     */
    public void setVideoEncoding(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>public.asset.video_encoding</code>.
     */
    public String getVideoEncoding() {
        return (String) get(27);
    }

    /**
     * Setter for <code>public.asset.image_dominant_color</code>.
     */
    public void setImageDominantColor(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>public.asset.image_dominant_color</code>.
     */
    public String getImageDominantColor() {
        return (String) get(28);
    }

    /**
     * Setter for <code>public.asset.image_encoding</code>.
     */
    public void setImageEncoding(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>public.asset.image_encoding</code>.
     */
    public String getImageEncoding() {
        return (String) get(29);
    }

    /**
     * Setter for <code>public.asset.image_fingerprint</code>. Image fingerprint
     * information
     */
    public void setImageFingerprint(String value) {
        set(30, value);
    }

    /**
     * Getter for <code>public.asset.image_fingerprint</code>. Image fingerprint
     * information
     */
    public String getImageFingerprint() {
        return (String) get(30);
    }

    /**
     * Setter for <code>public.asset.audio_bpm</code>.
     */
    public void setAudioBpm(Integer value) {
        set(31, value);
    }

    /**
     * Getter for <code>public.asset.audio_bpm</code>.
     */
    public Integer getAudioBpm() {
        return (Integer) get(31);
    }

    /**
     * Setter for <code>public.asset.audio_sampling_rate</code>.
     */
    public void setAudioSamplingRate(Integer value) {
        set(32, value);
    }

    /**
     * Getter for <code>public.asset.audio_sampling_rate</code>.
     */
    public Integer getAudioSamplingRate() {
        return (Integer) get(32);
    }

    /**
     * Setter for <code>public.asset.audio_channels</code>.
     */
    public void setAudioChannels(Integer value) {
        set(33, value);
    }

    /**
     * Getter for <code>public.asset.audio_channels</code>.
     */
    public Integer getAudioChannels() {
        return (Integer) get(33);
    }

    /**
     * Setter for <code>public.asset.audio_bitrate</code>.
     */
    public void setAudioBitrate(Integer value) {
        set(34, value);
    }

    /**
     * Getter for <code>public.asset.audio_bitrate</code>.
     */
    public Integer getAudioBitrate() {
        return (Integer) get(34);
    }

    /**
     * Setter for <code>public.asset.audio_encoding</code>. Store the audio
     * encoding used for the asset (e.g. mp3, flac)
     */
    public void setAudioEncoding(String value) {
        set(35, value);
    }

    /**
     * Getter for <code>public.asset.audio_encoding</code>. Store the audio
     * encoding used for the asset (e.g. mp3, flac)
     */
    public String getAudioEncoding() {
        return (String) get(35);
    }

    /**
     * Setter for <code>public.asset.audio_fingerprint</code>. Audio fingerprint
     * information
     */
    public void setAudioFingerprint(String value) {
        set(36, value);
    }

    /**
     * Getter for <code>public.asset.audio_fingerprint</code>. Audio fingerprint
     * information
     */
    public String getAudioFingerprint() {
        return (String) get(36);
    }

    /**
     * Setter for <code>public.asset.doc_plain_text</code>. Extracted text of
     * the document
     */
    public void setDocPlainText(String value) {
        set(37, value);
    }

    /**
     * Getter for <code>public.asset.doc_plain_text</code>. Extracted text of
     * the document
     */
    public String getDocPlainText() {
        return (String) get(37);
    }

    /**
     * Setter for <code>public.asset.doc_word_count</code>.
     */
    public void setDocWordCount(Integer value) {
        set(38, value);
    }

    /**
     * Getter for <code>public.asset.doc_word_count</code>.
     */
    public Integer getDocWordCount() {
        return (Integer) get(38);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JooqAssetRecord
     */
    public JooqAssetRecord() {
        super(JooqAsset.ASSET);
    }

    /**
     * Create a detached, initialised JooqAssetRecord
     */
    public JooqAssetRecord(UUID uuid, String sha512sum, Long size, String sha256sum, String md5sum, String chunkHash, Long zeroChunkCount, String mimeType, JSONB meta, String author, BigDecimal geoLon, BigDecimal geoLat, String geoAlias, String initialOrigin, LocalDateTime created, UUID creatorUuid, LocalDateTime edited, UUID editorUuid, String s3BucketName, String s3ObjectPath, Integer mediaWidth, Integer mediaHeight, Integer mediaDuration, Integer videoWidth, Integer videoHeight, String videoFingerprint, Integer videoBitrate, String videoEncoding, String imageDominantColor, String imageEncoding, String imageFingerprint, Integer audioBpm, Integer audioSamplingRate, Integer audioChannels, Integer audioBitrate, String audioEncoding, String audioFingerprint, String docPlainText, Integer docWordCount) {
        super(JooqAsset.ASSET);

        setUuid(uuid);
        setSha512sum(sha512sum);
        setSize(size);
        setSha256sum(sha256sum);
        setMd5sum(md5sum);
        setChunkHash(chunkHash);
        setZeroChunkCount(zeroChunkCount);
        setMimeType(mimeType);
        setMeta(meta);
        setAuthor(author);
        setGeoLon(geoLon);
        setGeoLat(geoLat);
        setGeoAlias(geoAlias);
        setInitialOrigin(initialOrigin);
        setCreated(created);
        setCreatorUuid(creatorUuid);
        setEdited(edited);
        setEditorUuid(editorUuid);
        setS3BucketName(s3BucketName);
        setS3ObjectPath(s3ObjectPath);
        setMediaWidth(mediaWidth);
        setMediaHeight(mediaHeight);
        setMediaDuration(mediaDuration);
        setVideoWidth(videoWidth);
        setVideoHeight(videoHeight);
        setVideoFingerprint(videoFingerprint);
        setVideoBitrate(videoBitrate);
        setVideoEncoding(videoEncoding);
        setImageDominantColor(imageDominantColor);
        setImageEncoding(imageEncoding);
        setImageFingerprint(imageFingerprint);
        setAudioBpm(audioBpm);
        setAudioSamplingRate(audioSamplingRate);
        setAudioChannels(audioChannels);
        setAudioBitrate(audioBitrate);
        setAudioEncoding(audioEncoding);
        setAudioFingerprint(audioFingerprint);
        setDocPlainText(docPlainText);
        setDocWordCount(docWordCount);
    }
}
