/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq.tables.records;


import io.metaloom.loom.db.jooq.tables.Namespaces;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NamespacesRecord extends UpdatableRecordImpl<NamespacesRecord> implements Record10<UUID, String, UUID, JSONB, String, String, LocalDateTime, UUID, LocalDateTime, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.namespaces.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.namespaces.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.namespaces.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.namespaces.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.namespaces.root_content_uuid</code>.
     */
    public void setRootContentUuid(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.namespaces.root_content_uuid</code>.
     */
    public UUID getRootContentUuid() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.namespaces.meta</code>. Custom meta properties to
     * the element
     */
    public void setMeta(JSONB value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.namespaces.meta</code>. Custom meta properties to
     * the element
     */
    public JSONB getMeta() {
        return (JSONB) get(3);
    }

    /**
     * Setter for <code>public.namespaces.path_prefix</code>. Prefix for webroot
     * paths
     */
    public void setPathPrefix(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.namespaces.path_prefix</code>. Prefix for webroot
     * paths
     */
    public String getPathPrefix() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.namespaces.model_filters</code>. filter for
     * models that can be used in the namespace
     */
    public void setModelFilters(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.namespaces.model_filters</code>. filter for
     * models that can be used in the namespace
     */
    public String getModelFilters() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.namespaces.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.namespaces.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.namespaces.creator_uuid</code>.
     */
    public void setCreatorUuid(UUID value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.namespaces.creator_uuid</code>.
     */
    public UUID getCreatorUuid() {
        return (UUID) get(7);
    }

    /**
     * Setter for <code>public.namespaces.edited</code>.
     */
    public void setEdited(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.namespaces.edited</code>.
     */
    public LocalDateTime getEdited() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>public.namespaces.editor_uuid</code>.
     */
    public void setEditorUuid(UUID value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.namespaces.editor_uuid</code>.
     */
    public UUID getEditorUuid() {
        return (UUID) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<UUID, String, UUID, JSONB, String, String, LocalDateTime, UUID, LocalDateTime, UUID> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<UUID, String, UUID, JSONB, String, String, LocalDateTime, UUID, LocalDateTime, UUID> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Namespaces.NAMESPACES.UUID;
    }

    @Override
    public Field<String> field2() {
        return Namespaces.NAMESPACES.NAME;
    }

    @Override
    public Field<UUID> field3() {
        return Namespaces.NAMESPACES.ROOT_CONTENT_UUID;
    }

    @Override
    public Field<JSONB> field4() {
        return Namespaces.NAMESPACES.META;
    }

    @Override
    public Field<String> field5() {
        return Namespaces.NAMESPACES.PATH_PREFIX;
    }

    @Override
    public Field<String> field6() {
        return Namespaces.NAMESPACES.MODEL_FILTERS;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Namespaces.NAMESPACES.CREATED;
    }

    @Override
    public Field<UUID> field8() {
        return Namespaces.NAMESPACES.CREATOR_UUID;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return Namespaces.NAMESPACES.EDITED;
    }

    @Override
    public Field<UUID> field10() {
        return Namespaces.NAMESPACES.EDITOR_UUID;
    }

    @Override
    public UUID component1() {
        return getUuid();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public UUID component3() {
        return getRootContentUuid();
    }

    @Override
    public JSONB component4() {
        return getMeta();
    }

    @Override
    public String component5() {
        return getPathPrefix();
    }

    @Override
    public String component6() {
        return getModelFilters();
    }

    @Override
    public LocalDateTime component7() {
        return getCreated();
    }

    @Override
    public UUID component8() {
        return getCreatorUuid();
    }

    @Override
    public LocalDateTime component9() {
        return getEdited();
    }

    @Override
    public UUID component10() {
        return getEditorUuid();
    }

    @Override
    public UUID value1() {
        return getUuid();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public UUID value3() {
        return getRootContentUuid();
    }

    @Override
    public JSONB value4() {
        return getMeta();
    }

    @Override
    public String value5() {
        return getPathPrefix();
    }

    @Override
    public String value6() {
        return getModelFilters();
    }

    @Override
    public LocalDateTime value7() {
        return getCreated();
    }

    @Override
    public UUID value8() {
        return getCreatorUuid();
    }

    @Override
    public LocalDateTime value9() {
        return getEdited();
    }

    @Override
    public UUID value10() {
        return getEditorUuid();
    }

    @Override
    public NamespacesRecord value1(UUID value) {
        setUuid(value);
        return this;
    }

    @Override
    public NamespacesRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public NamespacesRecord value3(UUID value) {
        setRootContentUuid(value);
        return this;
    }

    @Override
    public NamespacesRecord value4(JSONB value) {
        setMeta(value);
        return this;
    }

    @Override
    public NamespacesRecord value5(String value) {
        setPathPrefix(value);
        return this;
    }

    @Override
    public NamespacesRecord value6(String value) {
        setModelFilters(value);
        return this;
    }

    @Override
    public NamespacesRecord value7(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public NamespacesRecord value8(UUID value) {
        setCreatorUuid(value);
        return this;
    }

    @Override
    public NamespacesRecord value9(LocalDateTime value) {
        setEdited(value);
        return this;
    }

    @Override
    public NamespacesRecord value10(UUID value) {
        setEditorUuid(value);
        return this;
    }

    @Override
    public NamespacesRecord values(UUID value1, String value2, UUID value3, JSONB value4, String value5, String value6, LocalDateTime value7, UUID value8, LocalDateTime value9, UUID value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NamespacesRecord
     */
    public NamespacesRecord() {
        super(Namespaces.NAMESPACES);
    }

    /**
     * Create a detached, initialised NamespacesRecord
     */
    public NamespacesRecord(UUID uuid, String name, UUID rootContentUuid, JSONB meta, String pathPrefix, String modelFilters, LocalDateTime created, UUID creatorUuid, LocalDateTime edited, UUID editorUuid) {
        super(Namespaces.NAMESPACES);

        setUuid(uuid);
        setName(name);
        setRootContentUuid(rootContentUuid);
        setMeta(meta);
        setPathPrefix(pathPrefix);
        setModelFilters(modelFilters);
        setCreated(created);
        setCreatorUuid(creatorUuid);
        setEdited(edited);
        setEditorUuid(editorUuid);
    }
}
