/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq;


import io.metaloom.loom.db.jooq.tables.JooqAsset;
import io.metaloom.loom.db.jooq.tables.JooqFieldContent;
import io.metaloom.loom.db.jooq.tables.JooqFlywaySchemaHistory;
import io.metaloom.loom.db.jooq.tables.JooqGroup;
import io.metaloom.loom.db.jooq.tables.JooqLanguage;
import io.metaloom.loom.db.jooq.tables.JooqModel;
import io.metaloom.loom.db.jooq.tables.JooqNamespace;
import io.metaloom.loom.db.jooq.tables.JooqRole;
import io.metaloom.loom.db.jooq.tables.JooqTag;
import io.metaloom.loom.db.jooq.tables.JooqUser;
import io.metaloom.loom.db.jooq.tables.JooqUserToken;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ASSET_UUID_NAMESPACE_UUID_IDX = Internal.createIndex(DSL.name("asset_uuid_namespace_uuid_idx"), JooqAsset.ASSET, new OrderField[] { JooqAsset.ASSET.UUID, JooqAsset.ASSET.NAMESPACE_UUID }, true);
    public static final Index FIELD_CONTENT_CONTENT_TYPE_WEBROOT_PATH_INFO_IDX = Internal.createIndex(DSL.name("field_content_content_type_webroot_path_info_idx"), JooqFieldContent.FIELD_CONTENT, new OrderField[] { JooqFieldContent.FIELD_CONTENT.CONTENT_TYPE, JooqFieldContent.FIELD_CONTENT.WEBROOT_PATH_INFO }, false);
    public static final Index FIELD_CONTENT_CONTENT_UUID_CONTENT_TYPE_IDX = Internal.createIndex(DSL.name("field_content_content_uuid_content_type_idx"), JooqFieldContent.FIELD_CONTENT, new OrderField[] { JooqFieldContent.FIELD_CONTENT.CONTENT_UUID, JooqFieldContent.FIELD_CONTENT.CONTENT_TYPE }, false);
    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), JooqFlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { JooqFlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
    public static final Index GROUP_NAME_IDX = Internal.createIndex(DSL.name("group_name_idx"), JooqGroup.GROUP, new OrderField[] { JooqGroup.GROUP.NAME }, true);
    public static final Index LANGUAGE_TAG_IDX = Internal.createIndex(DSL.name("language_tag_idx"), JooqLanguage.LANGUAGE, new OrderField[] { JooqLanguage.LANGUAGE.TAG }, false);
    public static final Index MODEL_NAME_IDX = Internal.createIndex(DSL.name("model_name_idx"), JooqModel.MODEL, new OrderField[] { JooqModel.MODEL.NAME }, true);
    public static final Index NAMESPACE_NAME_IDX = Internal.createIndex(DSL.name("namespace_name_idx"), JooqNamespace.NAMESPACE, new OrderField[] { JooqNamespace.NAMESPACE.NAME }, true);
    public static final Index ROLE_NAME_IDX = Internal.createIndex(DSL.name("role_name_idx"), JooqRole.ROLE, new OrderField[] { JooqRole.ROLE.NAME }, true);
    public static final Index TAG_NAME_COLLECTION_NAMESPACE_UUID_IDX = Internal.createIndex(DSL.name("tag_name_collection_namespace_uuid_idx"), JooqTag.TAG, new OrderField[] { JooqTag.TAG.NAME, JooqTag.TAG.COLLECTION, JooqTag.TAG.NAMESPACE_UUID }, true);
    public static final Index USER_TOKEN_USER_UUID_IDX = Internal.createIndex(DSL.name("user_token_user_uuid_idx"), JooqUserToken.USER_TOKEN, new OrderField[] { JooqUserToken.USER_TOKEN.USER_UUID }, false);
    public static final Index USER_USERNAME_IDX = Internal.createIndex(DSL.name("user_username_idx"), JooqUser.USER, new OrderField[] { JooqUser.USER.USERNAME }, true);
}
