/*
 * This file is generated by jOOQ.
 */
package io.metaloom.loom.db.jooq;


import io.metaloom.loom.db.jooq.tables.Asset;
import io.metaloom.loom.db.jooq.tables.AssetBinary;
import io.metaloom.loom.db.jooq.tables.AssetTimeline;
import io.metaloom.loom.db.jooq.tables.AssetTimelineTag;
import io.metaloom.loom.db.jooq.tables.AssetUserMeta;
import io.metaloom.loom.db.jooq.tables.Content;
import io.metaloom.loom.db.jooq.tables.ContentUserMeta;
import io.metaloom.loom.db.jooq.tables.Extension;
import io.metaloom.loom.db.jooq.tables.Field;
import io.metaloom.loom.db.jooq.tables.FieldAsset;
import io.metaloom.loom.db.jooq.tables.FieldContent;
import io.metaloom.loom.db.jooq.tables.FieldReference;
import io.metaloom.loom.db.jooq.tables.FlywaySchemaHistory;
import io.metaloom.loom.db.jooq.tables.Group;
import io.metaloom.loom.db.jooq.tables.Language;
import io.metaloom.loom.db.jooq.tables.Loom;
import io.metaloom.loom.db.jooq.tables.Model;
import io.metaloom.loom.db.jooq.tables.ModelVersion;
import io.metaloom.loom.db.jooq.tables.Namespace;
import io.metaloom.loom.db.jooq.tables.Role;
import io.metaloom.loom.db.jooq.tables.RoleGroup;
import io.metaloom.loom.db.jooq.tables.RolePermission;
import io.metaloom.loom.db.jooq.tables.Tag;
import io.metaloom.loom.db.jooq.tables.TagAsset;
import io.metaloom.loom.db.jooq.tables.TagContent;
import io.metaloom.loom.db.jooq.tables.TagNamespace;
import io.metaloom.loom.db.jooq.tables.TagUserMeta;
import io.metaloom.loom.db.jooq.tables.User;
import io.metaloom.loom.db.jooq.tables.UserGroup;
import io.metaloom.loom.db.jooq.tables.UserToken;
import io.metaloom.loom.db.jooq.tables.Webhook;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.asset</code>.
     */
    public static final Asset ASSET = Asset.ASSET;

    /**
     * This table stores the immutable asset information
     */
    public static final AssetBinary ASSET_BINARY = AssetBinary.ASSET_BINARY;

    /**
     * This table contains asset timeline entries
     */
    public static final AssetTimeline ASSET_TIMELINE = AssetTimeline.ASSET_TIMELINE;

    /**
     * The table <code>public.asset_timeline_tag</code>.
     */
    public static final AssetTimelineTag ASSET_TIMELINE_TAG = AssetTimelineTag.ASSET_TIMELINE_TAG;

    /**
     * The table <code>public.asset_user_meta</code>.
     */
    public static final AssetUserMeta ASSET_USER_META = AssetUserMeta.ASSET_USER_META;

    /**
     * The table <code>public.content</code>.
     */
    public static final Content CONTENT = Content.CONTENT;

    /**
     * The table <code>public.content_user_meta</code>.
     */
    public static final ContentUserMeta CONTENT_USER_META = ContentUserMeta.CONTENT_USER_META;

    /**
     * Table which lists the registered extensions
     */
    public static final Extension EXTENSION = Extension.EXTENSION;

    /**
     * Table which stores the actual fields content as JSON
     */
    public static final Field FIELD = Field.FIELD;

    /**
     * Crosstable which tracks the used assets in a fields record
     */
    public static final FieldAsset FIELD_ASSET = FieldAsset.FIELD_ASSET;

    /**
     * Crosstable that tracks all fields for a content
     */
    public static final FieldContent FIELD_CONTENT = FieldContent.FIELD_CONTENT;

    /**
     * This table is mainly used to lookup foreign references to contents
     */
    public static final FieldReference FIELD_REFERENCE = FieldReference.FIELD_REFERENCE;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.group</code>.
     */
    public static final Group GROUP = Group.GROUP;

    /**
     * Table which stores the languages for loom
     */
    public static final Language LANGUAGE = Language.LANGUAGE;

    /**
     * The table <code>public.loom</code>.
     */
    public static final Loom LOOM = Loom.LOOM;

    /**
     * The table <code>public.model</code>.
     */
    public static final Model MODEL = Model.MODEL;

    /**
     * The table <code>public.model_version</code>.
     */
    public static final ModelVersion MODEL_VERSION = ModelVersion.MODEL_VERSION;

    /**
     * The table <code>public.namespace</code>.
     */
    public static final Namespace NAMESPACE = Namespace.NAMESPACE;

    /**
     * The table <code>public.role</code>.
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * The table <code>public.role_group</code>.
     */
    public static final RoleGroup ROLE_GROUP = RoleGroup.ROLE_GROUP;

    /**
     * The table <code>public.role_permission</code>.
     */
    public static final RolePermission ROLE_PERMISSION = RolePermission.ROLE_PERMISSION;

    /**
     * The table <code>public.tag</code>.
     */
    public static final Tag TAG = Tag.TAG;

    /**
     * The table <code>public.tag_asset</code>.
     */
    public static final TagAsset TAG_ASSET = TagAsset.TAG_ASSET;

    /**
     * The table <code>public.tag_content</code>.
     */
    public static final TagContent TAG_CONTENT = TagContent.TAG_CONTENT;

    /**
     * Table used to taggings on namespaces
     */
    public static final TagNamespace TAG_NAMESPACE = TagNamespace.TAG_NAMESPACE;

    /**
     * The table <code>public.tag_user_meta</code>.
     */
    public static final TagUserMeta TAG_USER_META = TagUserMeta.TAG_USER_META;

    /**
     * The table <code>public.user</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>public.user_group</code>.
     */
    public static final UserGroup USER_GROUP = UserGroup.USER_GROUP;

    /**
     * The table <code>public.user_token</code>.
     */
    public static final UserToken USER_TOKEN = UserToken.USER_TOKEN;

    /**
     * Table which stores the registered webhooks
     */
    public static final Webhook WEBHOOK = Webhook.WEBHOOK;
}
